// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_frmbuf_wr_0_0_MultiPixStream2Bytes (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_dout,
        img_num_data_valid,
        img_fifo_cap,
        img_empty_n,
        img_read,
        bytePlanes_plane0_din,
        bytePlanes_plane0_num_data_valid,
        bytePlanes_plane0_fifo_cap,
        bytePlanes_plane0_full_n,
        bytePlanes_plane0_write,
        bytePlanes_plane1_din,
        bytePlanes_plane1_num_data_valid,
        bytePlanes_plane1_fifo_cap,
        bytePlanes_plane1_full_n,
        bytePlanes_plane1_write,
        Height_dout,
        Height_num_data_valid,
        Height_fifo_cap,
        Height_empty_n,
        Height_read,
        WidthInBytes_dout,
        WidthInBytes_num_data_valid,
        WidthInBytes_fifo_cap,
        WidthInBytes_empty_n,
        WidthInBytes_read,
        VideoFormat_dout,
        VideoFormat_num_data_valid,
        VideoFormat_fifo_cap,
        VideoFormat_empty_n,
        VideoFormat_read,
        WidthInBytes_c_din,
        WidthInBytes_c_num_data_valid,
        WidthInBytes_c_fifo_cap,
        WidthInBytes_c_full_n,
        WidthInBytes_c_write,
        height_c_din,
        height_c_num_data_valid,
        height_c_fifo_cap,
        height_c_full_n,
        height_c_write,
        video_format_c_din,
        video_format_c_num_data_valid,
        video_format_c_fifo_cap,
        video_format_c_full_n,
        video_format_c_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] img_dout;
input  [1:0] img_num_data_valid;
input  [1:0] img_fifo_cap;
input   img_empty_n;
output   img_read;
output  [63:0] bytePlanes_plane0_din;
input  [10:0] bytePlanes_plane0_num_data_valid;
input  [10:0] bytePlanes_plane0_fifo_cap;
input   bytePlanes_plane0_full_n;
output   bytePlanes_plane0_write;
output  [63:0] bytePlanes_plane1_din;
input  [10:0] bytePlanes_plane1_num_data_valid;
input  [10:0] bytePlanes_plane1_fifo_cap;
input   bytePlanes_plane1_full_n;
output   bytePlanes_plane1_write;
input  [11:0] Height_dout;
input  [1:0] Height_num_data_valid;
input  [1:0] Height_fifo_cap;
input   Height_empty_n;
output   Height_read;
input  [14:0] WidthInBytes_dout;
input  [2:0] WidthInBytes_num_data_valid;
input  [2:0] WidthInBytes_fifo_cap;
input   WidthInBytes_empty_n;
output   WidthInBytes_read;
input  [5:0] VideoFormat_dout;
input  [2:0] VideoFormat_num_data_valid;
input  [2:0] VideoFormat_fifo_cap;
input   VideoFormat_empty_n;
output   VideoFormat_read;
output  [14:0] WidthInBytes_c_din;
input  [1:0] WidthInBytes_c_num_data_valid;
input  [1:0] WidthInBytes_c_fifo_cap;
input   WidthInBytes_c_full_n;
output   WidthInBytes_c_write;
output  [11:0] height_c_din;
input  [1:0] height_c_num_data_valid;
input  [1:0] height_c_fifo_cap;
input   height_c_full_n;
output   height_c_write;
output  [5:0] video_format_c_din;
input  [1:0] video_format_c_num_data_valid;
input  [1:0] video_format_c_fifo_cap;
input   video_format_c_full_n;
output   video_format_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_read;
reg[63:0] bytePlanes_plane0_din;
reg bytePlanes_plane0_write;
reg bytePlanes_plane1_write;
reg Height_read;
reg WidthInBytes_read;
reg VideoFormat_read;
reg WidthInBytes_c_write;
reg height_c_write;
reg video_format_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Height_blk_n;
reg    WidthInBytes_blk_n;
reg    VideoFormat_blk_n;
reg    WidthInBytes_c_blk_n;
reg    height_c_blk_n;
reg    video_format_c_blk_n;
wire   [5:0] VideoFormat_read_read_fu_158_p2;
reg   [5:0] VideoFormat_read_reg_559;
reg    ap_block_state1;
reg   [11:0] Height_read_reg_564;
reg   [14:0] widthInPix_reg_571;
wire   [12:0] trunc_ln571_1_fu_274_p4;
reg   [12:0] trunc_ln571_1_reg_587;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln576_fu_288_p2;
reg   [0:0] icmp_ln576_reg_592;
wire   [12:0] sub209_fu_302_p2;
reg   [12:0] sub209_reg_597;
wire   [0:0] icmp11_fu_318_p2;
reg   [0:0] icmp11_reg_602;
wire   [0:0] cmp212_2_fu_324_p2;
reg   [0:0] cmp212_2_reg_607;
wire   [0:0] icmp14_fu_340_p2;
reg   [0:0] icmp14_reg_612;
wire   [0:0] cmp212_4_fu_346_p2;
reg   [0:0] cmp212_4_reg_617;
wire   [0:0] cmp212_5_fu_352_p2;
reg   [0:0] cmp212_5_reg_622;
wire   [0:0] cmp212_6_fu_358_p2;
reg   [0:0] cmp212_6_reg_627;
wire   [12:0] trunc_ln534_1_fu_378_p4;
reg   [12:0] trunc_ln534_1_reg_639;
wire   [0:0] grp_fu_256_p2;
reg   [0:0] icmp_ln539_reg_644;
wire   [12:0] sub118_fu_400_p2;
reg   [12:0] sub118_reg_649;
wire   [0:0] icmp8_fu_416_p2;
reg   [0:0] icmp8_reg_654;
wire   [0:0] cmp121_2_fu_422_p2;
reg   [0:0] cmp121_2_reg_659;
wire   [12:0] trunc_ln496_1_fu_442_p4;
reg   [12:0] trunc_ln496_1_reg_671;
reg   [0:0] icmp_ln501_reg_676;
wire   [12:0] sub40_fu_464_p2;
reg   [12:0] sub40_reg_681;
wire   [0:0] icmp_fu_480_p2;
reg   [0:0] icmp_reg_686;
wire   [0:0] cmp43_2_fu_486_p2;
reg   [0:0] cmp43_2_reg_691;
wire   [0:0] trunc_ln583_fu_500_p1;
reg   [0:0] trunc_ln583_reg_696;
wire    ap_CS_fsm_state3;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_write;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_write;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_write;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_write;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg;
wire   [0:0] icmp_ln583_fu_505_p2;
wire    ap_CS_fsm_state4;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg;
wire   [0:0] icmp_ln546_fu_524_p2;
wire    ap_CS_fsm_state5;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg;
wire   [0:0] icmp_ln508_fu_543_p2;
wire    ap_CS_fsm_state6;
reg   [11:0] y_2_fu_146;
wire   [11:0] y_8_fu_510_p2;
reg   [11:0] y_1_fu_150;
wire   [11:0] y_6_fu_529_p2;
reg   [11:0] y_fu_154;
wire   [11:0] y_4_fu_548_p2;
wire   [1:0] grp_fu_247_p4;
wire   [15:0] zext_ln571_fu_265_p1;
wire   [15:0] add_ln571_fu_268_p2;
wire   [2:0] remainPix_4_fu_262_p1;
wire   [3:0] zext_ln574_fu_284_p1;
wire   [3:0] remainPix_5_fu_294_p3;
wire   [2:0] tmp_2_fu_308_p4;
wire   [1:0] tmp_3_fu_330_p4;
wire   [15:0] zext_ln534_fu_369_p1;
wire   [15:0] add_ln534_fu_372_p2;
wire   [2:0] zext_ln537_fu_388_p1;
wire   [2:0] remainPix_3_fu_392_p3;
wire   [1:0] tmp_1_fu_406_p4;
wire   [15:0] zext_ln496_fu_433_p1;
wire   [15:0] add_ln496_fu_436_p2;
wire   [2:0] zext_ln499_fu_452_p1;
wire   [2:0] remainPix_1_fu_456_p3;
wire   [1:0] tmp_fu_470_p4;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg = 1'b0;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg = 1'b0;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg = 1'b0;
end

system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_img_read),
    .bytePlanes_plane0_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_din),
    .bytePlanes_plane0_num_data_valid(11'd0),
    .bytePlanes_plane0_fifo_cap(11'd0),
    .bytePlanes_plane0_full_n(bytePlanes_plane0_full_n),
    .bytePlanes_plane0_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_write),
    .bytePlanes_plane1_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_din),
    .bytePlanes_plane1_num_data_valid(11'd0),
    .bytePlanes_plane1_fifo_cap(11'd0),
    .bytePlanes_plane1_full_n(bytePlanes_plane1_full_n),
    .bytePlanes_plane1_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_write),
    .trunc_ln571_1(trunc_ln571_1_reg_587),
    .VideoFormat_load(VideoFormat_read_reg_559),
    .trunc_ln(trunc_ln583_reg_696),
    .icmp_ln576(icmp_ln576_reg_592),
    .cmp212_6(cmp212_6_reg_627),
    .cmp212_5(cmp212_5_reg_622),
    .cmp212_4(cmp212_4_reg_617),
    .cmp212_3(icmp14_reg_612),
    .cmp212_2(cmp212_2_reg_607),
    .sub209_cast62(sub209_reg_597),
    .cmp212_1(icmp11_reg_602)
);

system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_img_read),
    .bytePlanes_plane0_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_din),
    .bytePlanes_plane0_num_data_valid(11'd0),
    .bytePlanes_plane0_fifo_cap(11'd0),
    .bytePlanes_plane0_full_n(bytePlanes_plane0_full_n),
    .bytePlanes_plane0_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_write),
    .trunc_ln534_1(trunc_ln534_1_reg_639),
    .icmp_ln539(icmp_ln539_reg_644),
    .cmp121_2(cmp121_2_reg_659),
    .sub118_cast59(sub118_reg_649),
    .cmp121_1(icmp8_reg_654)
);

system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_img_read),
    .bytePlanes_plane0_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_din),
    .bytePlanes_plane0_num_data_valid(11'd0),
    .bytePlanes_plane0_fifo_cap(11'd0),
    .bytePlanes_plane0_full_n(bytePlanes_plane0_full_n),
    .bytePlanes_plane0_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_write),
    .trunc_ln496_1(trunc_ln496_1_reg_671),
    .icmp_ln501(icmp_ln501_reg_676),
    .cmp43_2(cmp43_2_reg_691),
    .sub40_cast56(sub40_reg_681),
    .cmp43_1(icmp_reg_686)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & ((((((icmp_ln583_fu_505_p2 == 1'd1) & (6'd19 == VideoFormat_read_reg_559)) | ((icmp_ln583_fu_505_p2 == 1'd1) & (6'd18 == VideoFormat_read_reg_559))) | (~(6'd28 == VideoFormat_read_reg_559) & ~(6'd19 == VideoFormat_read_reg_559) & ~(6'd18 == VideoFormat_read_reg_559) & (icmp_ln508_fu_543_p2 == 1'd1))) | ((icmp_ln546_fu_524_p2 == 1'd1) & (6'd28 == VideoFormat_read_reg_559))) | (~(6'd12 == VideoFormat_read_reg_559) & ~(6'd28 == VideoFormat_read_reg_559) & ~(6'd19 == VideoFormat_read_reg_559) & ~(6'd18 == VideoFormat_read_reg_559))))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln508_fu_543_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (6'd12 == VideoFormat_read_reg_559))) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln546_fu_524_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (6'd28 == VideoFormat_read_reg_559))) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln583_fu_505_p2 == 1'd0) & (6'd19 == VideoFormat_read_reg_559)) | ((icmp_ln583_fu_505_p2 == 1'd0) & (6'd18 == VideoFormat_read_reg_559))))) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((6'd28 == VideoFormat_read_reg_559)) begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            y_1_fu_150 <= 12'd0;
        end else if (((icmp_ln546_fu_524_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            y_1_fu_150 <= y_6_fu_529_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((6'd19 == VideoFormat_read_reg_559) | (6'd18 == VideoFormat_read_reg_559)))) begin
        y_2_fu_146 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((icmp_ln583_fu_505_p2 == 1'd0) & (6'd19 == VideoFormat_read_reg_559)) | ((icmp_ln583_fu_505_p2 == 1'd0) & (6'd18 == VideoFormat_read_reg_559))))) begin
        y_2_fu_146 <= y_8_fu_510_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((6'd12 == VideoFormat_read_reg_559)) begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            y_fu_154 <= 12'd0;
        end else if (((icmp_ln508_fu_543_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            y_fu_154 <= y_4_fu_548_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read_reg_564 <= Height_dout;
        VideoFormat_read_reg_559 <= VideoFormat_dout;
        widthInPix_reg_571 <= WidthInBytes_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (6'd28 == VideoFormat_read_reg_559))) begin
        cmp121_2_reg_659 <= cmp121_2_fu_422_p2;
        icmp8_reg_654 <= icmp8_fu_416_p2;
        icmp_ln539_reg_644 <= grp_fu_256_p2;
        sub118_reg_649 <= sub118_fu_400_p2;
        trunc_ln534_1_reg_639 <= {{add_ln534_fu_372_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((6'd19 == VideoFormat_read_reg_559) | (6'd18 == VideoFormat_read_reg_559)))) begin
        cmp212_2_reg_607 <= cmp212_2_fu_324_p2;
        cmp212_4_reg_617 <= cmp212_4_fu_346_p2;
        cmp212_5_reg_622 <= cmp212_5_fu_352_p2;
        cmp212_6_reg_627 <= cmp212_6_fu_358_p2;
        icmp11_reg_602 <= icmp11_fu_318_p2;
        icmp14_reg_612 <= icmp14_fu_340_p2;
        icmp_ln576_reg_592 <= icmp_ln576_fu_288_p2;
        sub209_reg_597 <= sub209_fu_302_p2;
        trunc_ln571_1_reg_587 <= {{add_ln571_fu_268_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (6'd12 == VideoFormat_read_reg_559))) begin
        cmp43_2_reg_691 <= cmp43_2_fu_486_p2;
        icmp_ln501_reg_676 <= grp_fu_256_p2;
        icmp_reg_686 <= icmp_fu_480_p2;
        sub40_reg_681 <= sub40_fu_464_p2;
        trunc_ln496_1_reg_671 <= {{add_ln496_fu_436_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((6'd19 == VideoFormat_read_reg_559) | (6'd18 == VideoFormat_read_reg_559)))) begin
        trunc_ln583_reg_696 <= trunc_ln583_fu_500_p1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_blk_n = Height_empty_n;
    end else begin
        Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read = 1'b1;
    end else begin
        Height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_blk_n = VideoFormat_empty_n;
    end else begin
        VideoFormat_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_read = 1'b1;
    end else begin
        VideoFormat_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_blk_n = WidthInBytes_empty_n;
    end else begin
        WidthInBytes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_c_blk_n = WidthInBytes_c_full_n;
    end else begin
        WidthInBytes_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_c_write = 1'b1;
    end else begin
        WidthInBytes_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_read = 1'b1;
    end else begin
        WidthInBytes_read = 1'b0;
    end
end

always @ (*) begin
    if (((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((((((icmp_ln583_fu_505_p2 == 1'd1) & (6'd19 == VideoFormat_read_reg_559)) | ((icmp_ln583_fu_505_p2 == 1'd1) & (6'd18 == VideoFormat_read_reg_559))) | (~(6'd28 == VideoFormat_read_reg_559) & ~(6'd19 == VideoFormat_read_reg_559) & ~(6'd18 == VideoFormat_read_reg_559) & (icmp_ln508_fu_543_p2 == 1'd1))) | ((icmp_ln546_fu_524_p2 == 1'd1) & (6'd28 == VideoFormat_read_reg_559))) | (~(6'd12 == VideoFormat_read_reg_559) & ~(6'd28 == VideoFormat_read_reg_559) & ~(6'd19 == VideoFormat_read_reg_559) & ~(6'd18 == VideoFormat_read_reg_559))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((((((icmp_ln583_fu_505_p2 == 1'd1) & (6'd19 == VideoFormat_read_reg_559)) | ((icmp_ln583_fu_505_p2 == 1'd1) & (6'd18 == VideoFormat_read_reg_559))) | (~(6'd28 == VideoFormat_read_reg_559) & ~(6'd19 == VideoFormat_read_reg_559) & ~(6'd18 == VideoFormat_read_reg_559) & (icmp_ln508_fu_543_p2 == 1'd1))) | ((icmp_ln546_fu_524_p2 == 1'd1) & (6'd28 == VideoFormat_read_reg_559))) | (~(6'd12 == VideoFormat_read_reg_559) & ~(6'd28 == VideoFormat_read_reg_559) & ~(6'd19 == VideoFormat_read_reg_559) & ~(6'd18 == VideoFormat_read_reg_559))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        bytePlanes_plane0_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_din;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        bytePlanes_plane0_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_din;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bytePlanes_plane0_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_din;
    end else begin
        bytePlanes_plane0_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        bytePlanes_plane0_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_write;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        bytePlanes_plane0_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_write;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bytePlanes_plane0_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_write;
    end else begin
        bytePlanes_plane0_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bytePlanes_plane1_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_write;
    end else begin
        bytePlanes_plane1_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_blk_n = height_c_full_n;
    end else begin
        height_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_write = 1'b1;
    end else begin
        height_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_img_read;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_img_read;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_img_read;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        video_format_c_blk_n = video_format_c_full_n;
    end else begin
        video_format_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        video_format_c_write = 1'b1;
    end else begin
        video_format_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~(6'd12 == VideoFormat_read_read_fu_158_p2) & ~(6'd28 == VideoFormat_read_read_fu_158_p2) & ~(6'd19 == VideoFormat_read_read_fu_158_p2) & ~(6'd18 == VideoFormat_read_read_fu_158_p2) & ~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & ((6'd12 == VideoFormat_read_read_fu_158_p2) | ((6'd28 == VideoFormat_read_read_fu_158_p2) | ((6'd19 == VideoFormat_read_read_fu_158_p2) | (6'd18 == VideoFormat_read_read_fu_158_p2)))))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & ((((((icmp_ln583_fu_505_p2 == 1'd1) & (6'd19 == VideoFormat_read_reg_559)) | ((icmp_ln583_fu_505_p2 == 1'd1) & (6'd18 == VideoFormat_read_reg_559))) | (~(6'd28 == VideoFormat_read_reg_559) & ~(6'd19 == VideoFormat_read_reg_559) & ~(6'd18 == VideoFormat_read_reg_559) & (icmp_ln508_fu_543_p2 == 1'd1))) | ((icmp_ln546_fu_524_p2 == 1'd1) & (6'd28 == VideoFormat_read_reg_559))) | (~(6'd12 == VideoFormat_read_reg_559) & ~(6'd28 == VideoFormat_read_reg_559) & ~(6'd19 == VideoFormat_read_reg_559) & ~(6'd18 == VideoFormat_read_reg_559))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln508_fu_543_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (6'd12 == VideoFormat_read_reg_559))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else if (((icmp_ln546_fu_524_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3) & (6'd28 == VideoFormat_read_reg_559))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign VideoFormat_read_read_fu_158_p2 = VideoFormat_dout;

assign WidthInBytes_c_din = WidthInBytes_dout;

assign add_ln496_fu_436_p2 = (zext_ln496_fu_433_p1 + 16'd7);

assign add_ln534_fu_372_p2 = (zext_ln534_fu_369_p1 + 16'd7);

assign add_ln571_fu_268_p2 = (zext_ln571_fu_265_p1 + 16'd7);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((video_format_c_full_n == 1'b0) | (height_c_full_n == 1'b0) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == Height_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign bytePlanes_plane1_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_din;

assign cmp121_2_fu_422_p2 = ((remainPix_3_fu_392_p3 > 3'd2) ? 1'b1 : 1'b0);

assign cmp212_2_fu_324_p2 = ((remainPix_5_fu_294_p3 > 4'd2) ? 1'b1 : 1'b0);

assign cmp212_4_fu_346_p2 = ((remainPix_5_fu_294_p3 > 4'd4) ? 1'b1 : 1'b0);

assign cmp212_5_fu_352_p2 = ((remainPix_5_fu_294_p3 > 4'd5) ? 1'b1 : 1'b0);

assign cmp212_6_fu_358_p2 = ((remainPix_5_fu_294_p3 > 4'd6) ? 1'b1 : 1'b0);

assign cmp43_2_fu_486_p2 = ((remainPix_1_fu_456_p3 > 3'd2) ? 1'b1 : 1'b0);

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg;

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg;

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg;

assign grp_fu_247_p4 = {{widthInPix_reg_571[2:1]}};

assign grp_fu_256_p2 = ((grp_fu_247_p4 == 2'd0) ? 1'b1 : 1'b0);

assign height_c_din = Height_dout;

assign icmp11_fu_318_p2 = ((tmp_2_fu_308_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp14_fu_340_p2 = ((tmp_3_fu_330_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp8_fu_416_p2 = ((tmp_1_fu_406_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_fu_480_p2 = ((tmp_fu_470_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln508_fu_543_p2 = ((y_fu_154 == Height_read_reg_564) ? 1'b1 : 1'b0);

assign icmp_ln546_fu_524_p2 = ((y_1_fu_150 == Height_read_reg_564) ? 1'b1 : 1'b0);

assign icmp_ln576_fu_288_p2 = ((remainPix_4_fu_262_p1 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln583_fu_505_p2 = ((y_2_fu_146 == Height_read_reg_564) ? 1'b1 : 1'b0);

assign remainPix_1_fu_456_p3 = ((grp_fu_256_p2[0:0] == 1'b1) ? 3'd4 : zext_ln499_fu_452_p1);

assign remainPix_3_fu_392_p3 = ((grp_fu_256_p2[0:0] == 1'b1) ? 3'd4 : zext_ln537_fu_388_p1);

assign remainPix_4_fu_262_p1 = widthInPix_reg_571[2:0];

assign remainPix_5_fu_294_p3 = ((icmp_ln576_fu_288_p2[0:0] == 1'b1) ? 4'd8 : zext_ln574_fu_284_p1);

assign sub118_fu_400_p2 = ($signed(trunc_ln534_1_fu_378_p4) + $signed(13'd8191));

assign sub209_fu_302_p2 = ($signed(trunc_ln571_1_fu_274_p4) + $signed(13'd8191));

assign sub40_fu_464_p2 = ($signed(trunc_ln496_1_fu_442_p4) + $signed(13'd8191));

assign tmp_1_fu_406_p4 = {{remainPix_3_fu_392_p3[2:1]}};

assign tmp_2_fu_308_p4 = {{remainPix_5_fu_294_p3[3:1]}};

assign tmp_3_fu_330_p4 = {{remainPix_5_fu_294_p3[3:2]}};

assign tmp_fu_470_p4 = {{remainPix_1_fu_456_p3[2:1]}};

assign trunc_ln496_1_fu_442_p4 = {{add_ln496_fu_436_p2[15:3]}};

assign trunc_ln534_1_fu_378_p4 = {{add_ln534_fu_372_p2[15:3]}};

assign trunc_ln571_1_fu_274_p4 = {{add_ln571_fu_268_p2[15:3]}};

assign trunc_ln583_fu_500_p1 = y_2_fu_146[0:0];

assign video_format_c_din = VideoFormat_dout;

assign y_4_fu_548_p2 = (y_fu_154 + 12'd1);

assign y_6_fu_529_p2 = (y_1_fu_150 + 12'd1);

assign y_8_fu_510_p2 = (y_2_fu_146 + 12'd1);

assign zext_ln496_fu_433_p1 = widthInPix_reg_571;

assign zext_ln499_fu_452_p1 = grp_fu_247_p4;

assign zext_ln534_fu_369_p1 = widthInPix_reg_571;

assign zext_ln537_fu_388_p1 = grp_fu_247_p4;

assign zext_ln571_fu_265_p1 = widthInPix_reg_571;

assign zext_ln574_fu_284_p1 = remainPix_4_fu_262_p1;

endmodule //system_v_frmbuf_wr_0_0_MultiPixStream2Bytes
