// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        img_dout,
        img_num_data_valid,
        img_fifo_cap,
        img_empty_n,
        img_read,
        bytePlanes_plane0_din,
        bytePlanes_plane0_num_data_valid,
        bytePlanes_plane0_fifo_cap,
        bytePlanes_plane0_full_n,
        bytePlanes_plane0_write,
        trunc_ln496_1,
        icmp_ln501,
        cmp43_2,
        sub40_cast56,
        cmp43_1
);

parameter    ap_ST_fsm_pp0_stage0 = 4'd1;
parameter    ap_ST_fsm_pp0_stage1 = 4'd2;
parameter    ap_ST_fsm_pp0_stage2 = 4'd4;
parameter    ap_ST_fsm_pp0_stage3 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] img_dout;
input  [1:0] img_num_data_valid;
input  [1:0] img_fifo_cap;
input   img_empty_n;
output   img_read;
output  [63:0] bytePlanes_plane0_din;
input  [10:0] bytePlanes_plane0_num_data_valid;
input  [10:0] bytePlanes_plane0_fifo_cap;
input   bytePlanes_plane0_full_n;
output   bytePlanes_plane0_write;
input  [12:0] trunc_ln496_1;
input  [0:0] icmp_ln501;
input  [0:0] cmp43_2;
input  [12:0] sub40_cast56;
input  [0:0] cmp43_1;

reg ap_idle;
reg img_read;
reg bytePlanes_plane0_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
reg   [0:0] icmp_ln511_reg_292;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state6_pp0_stage1_iter1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage3;
reg   [0:0] or_ln516_1_reg_318;
reg    ap_predicate_op44_read_state4;
reg    ap_block_state4_pp0_stage3_iter0;
reg    ap_block_pp0_stage3_subdone;
reg    bytePlanes_plane0_blk_n;
wire    ap_block_pp0_stage1;
reg    img_blk_n;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2;
reg   [0:0] or_ln516_reg_314;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage0;
reg   [0:0] or_ln516_2_reg_322;
reg   [7:0] empty_140_reg_117;
reg   [7:0] empty_138_reg_136;
reg   [7:0] empty_139_reg_147;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_predicate_op52_read_state5;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln511_fu_199_p2;
wire   [0:0] cmp41_fu_215_p2;
reg   [0:0] cmp41_reg_296;
reg   [23:0] img_read_reg_303;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] or_ln516_fu_226_p2;
wire   [0:0] or_ln516_1_fu_230_p2;
wire   [0:0] or_ln516_2_fu_234_p2;
reg    ap_predicate_op37_read_state3;
reg    ap_block_state3_pp0_stage2_iter0;
reg    ap_block_pp0_stage2_11001;
wire   [7:0] trunc_ln517_fu_238_p1;
reg   [7:0] trunc_ln517_reg_336;
reg    ap_block_pp0_stage3_11001;
wire   [7:0] trunc_ln517_2_fu_242_p1;
wire   [15:0] trunc_ln526_fu_246_p1;
reg   [15:0] trunc_ln526_reg_352;
wire   [7:0] trunc_ln517_4_fu_249_p1;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [7:0] ap_phi_reg_pp0_iter0_empty_140_reg_117;
reg   [23:0] ap_phi_reg_pp0_iter0_p_in_reg_127;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_138_reg_136;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_138_reg_136;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_139_reg_147;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_139_reg_147;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_reg_157;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_reg_157;
wire   [7:0] ap_phi_reg_pp0_iter0_empty_137_reg_167;
reg   [7:0] ap_phi_reg_pp0_iter1_empty_137_reg_167;
reg   [12:0] x_fu_70;
wire   [12:0] x_5_fu_205_p2;
wire    ap_loop_init;
reg   [12:0] ap_sig_allocacmp_x_4;
reg    ap_block_pp0_stage1_01001;
wire   [13:0] zext_ln511_fu_211_p1;
wire  signed [13:0] sub40_cast56_cast_fu_187_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage2_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_212;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

system_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage3_subdone) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln511_reg_292 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln516_2_reg_322 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_empty_137_reg_167 <= ap_phi_reg_pp0_iter1_empty_139_reg_147;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln511_reg_292 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln516_2_reg_322 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_empty_137_reg_167 <= trunc_ln517_4_fu_249_p1;
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter1_empty_137_reg_167 <= ap_phi_reg_pp0_iter0_empty_137_reg_167;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if (((or_ln516_1_reg_318 == 1'd0) & (icmp_ln511_reg_292 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_138_reg_136 <= ap_phi_reg_pp0_iter0_empty_140_reg_117;
        end else if (((or_ln516_1_reg_318 == 1'd1) & (icmp_ln511_reg_292 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_138_reg_136 <= {{img_dout[15:8]}};
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_138_reg_136 <= ap_phi_reg_pp0_iter0_empty_138_reg_136;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_212)) begin
        if (((or_ln516_1_reg_318 == 1'd0) & (icmp_ln511_reg_292 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_139_reg_147 <= trunc_ln517_fu_238_p1;
        end else if (((or_ln516_1_reg_318 == 1'd1) & (icmp_ln511_reg_292 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_empty_139_reg_147 <= trunc_ln517_2_fu_242_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_empty_139_reg_147 <= ap_phi_reg_pp0_iter0_empty_139_reg_147;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln511_reg_292 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln516_2_reg_322 == 1'd0))) begin
        ap_phi_reg_pp0_iter1_empty_reg_157 <= ap_phi_reg_pp0_iter1_empty_138_reg_136;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln511_reg_292 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln516_2_reg_322 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_empty_reg_157 <= {{img_dout[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_phi_reg_pp0_iter1_empty_reg_157 <= ap_phi_reg_pp0_iter0_empty_reg_157;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln511_fu_199_p2 == 1'd0))) begin
            x_fu_70 <= x_5_fu_205_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_70 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (icmp_ln511_reg_292 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (or_ln516_reg_314 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln511_reg_292 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (or_ln516_fu_226_p2 == 1'd0)))) begin
        ap_phi_reg_pp0_iter0_empty_140_reg_117 <= {{img_dout[15:8]}};
        ap_phi_reg_pp0_iter0_p_in_reg_127 <= img_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln511_fu_199_p2 == 1'd0))) begin
        cmp41_reg_296 <= cmp41_fu_215_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        empty_138_reg_136 <= ap_phi_reg_pp0_iter1_empty_138_reg_136;
        empty_139_reg_147 <= ap_phi_reg_pp0_iter1_empty_139_reg_147;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        empty_140_reg_117 <= ap_phi_reg_pp0_iter0_empty_140_reg_117;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln511_reg_292 <= icmp_ln511_fu_199_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln511_reg_292 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        img_read_reg_303 <= img_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln511_reg_292 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        or_ln516_1_reg_318 <= or_ln516_1_fu_230_p2;
        or_ln516_2_reg_322 <= or_ln516_2_fu_234_p2;
        or_ln516_reg_314 <= or_ln516_fu_226_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (icmp_ln511_reg_292 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        trunc_ln517_reg_336 <= trunc_ln517_fu_238_p1;
        trunc_ln526_reg_352 <= trunc_ln526_fu_246_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_subdone) & (icmp_ln511_reg_292 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage3_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_4 = 13'd0;
    end else begin
        ap_sig_allocacmp_x_4 = x_fu_70;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_plane0_blk_n = bytePlanes_plane0_full_n;
    end else begin
        bytePlanes_plane0_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        bytePlanes_plane0_write = 1'b1;
    end else begin
        bytePlanes_plane0_write = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op44_read_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln511_reg_292 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln516_2_reg_322 == 1'd1)) | ((1'b0 == ap_block_pp0_stage2) & (icmp_ln511_reg_292 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (or_ln516_reg_314 == 1'd1)) | ((1'b0 == ap_block_pp0_stage1) & (icmp_ln511_reg_292 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        img_blk_n = img_empty_n;
    end else begin
        img_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op44_read_state4 == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_predicate_op37_read_state3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln511_reg_292 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op52_read_state5 == 1'b1)))) begin
        img_read = 1'b1;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage1)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op52_read_state5 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (ap_predicate_op52_read_state5 == 1'b1));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_01001 = (((bytePlanes_plane0_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln511_reg_292 == 1'd0) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((bytePlanes_plane0_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln511_reg_292 == 1'd0) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((bytePlanes_plane0_full_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((icmp_ln511_reg_292 == 1'd0) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001 = ((img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op37_read_state3 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (ap_predicate_op37_read_state3 == 1'b1));
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001 = ((ap_predicate_op44_read_state4 == 1'b1) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((ap_predicate_op44_read_state4 == 1'b1) & (img_empty_n == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((icmp_ln511_reg_292 == 1'd0) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0 = ((img_empty_n == 1'b0) & (ap_predicate_op37_read_state3 == 1'b1));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0 = ((ap_predicate_op44_read_state4 == 1'b1) & (img_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = ((img_empty_n == 1'b0) & (ap_predicate_op52_read_state5 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp0_stage1_iter1 = (bytePlanes_plane0_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_212 = ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_phi_reg_pp0_iter0_empty_137_reg_167 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_138_reg_136 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_139_reg_147 = 'bx;

assign ap_phi_reg_pp0_iter0_empty_reg_157 = 'bx;

always @ (*) begin
    ap_predicate_op37_read_state3 = ((icmp_ln511_reg_292 == 1'd0) & (or_ln516_reg_314 == 1'd1));
end

always @ (*) begin
    ap_predicate_op44_read_state4 = ((or_ln516_1_reg_318 == 1'd1) & (icmp_ln511_reg_292 == 1'd0));
end

always @ (*) begin
    ap_predicate_op52_read_state5 = ((icmp_ln511_reg_292 == 1'd0) & (or_ln516_2_reg_322 == 1'd1));
end

assign bytePlanes_plane0_din = {{{{{{{ap_phi_reg_pp0_iter1_empty_reg_157}, {ap_phi_reg_pp0_iter1_empty_137_reg_167}}, {empty_138_reg_136}}, {empty_139_reg_147}}, {empty_140_reg_117}}, {trunc_ln517_reg_336}}, {trunc_ln526_reg_352}};

assign cmp41_fu_215_p2 = (($signed(zext_ln511_fu_211_p1) < $signed(sub40_cast56_cast_fu_187_p1)) ? 1'b1 : 1'b0);

assign icmp_ln511_fu_199_p2 = ((ap_sig_allocacmp_x_4 == trunc_ln496_1) ? 1'b1 : 1'b0);

assign or_ln516_1_fu_230_p2 = (cmp43_2 | cmp41_reg_296);

assign or_ln516_2_fu_234_p2 = (icmp_ln501 | cmp41_reg_296);

assign or_ln516_fu_226_p2 = (cmp43_1 | cmp41_reg_296);

assign sub40_cast56_cast_fu_187_p1 = $signed(sub40_cast56);

assign trunc_ln517_2_fu_242_p1 = img_dout[7:0];

assign trunc_ln517_4_fu_249_p1 = img_dout[7:0];

assign trunc_ln517_fu_238_p1 = ap_phi_reg_pp0_iter0_p_in_reg_127[7:0];

assign trunc_ln526_fu_246_p1 = img_read_reg_303[15:0];

assign x_5_fu_205_p2 = (ap_sig_allocacmp_x_4 + 13'd1);

assign zext_ln511_fu_211_p1 = ap_sig_allocacmp_x_4;

endmodule //system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1
