-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity system_v_frmbuf_wr_0_0_MultiPixStream2Bytes is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    img_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_empty_n : IN STD_LOGIC;
    img_read : OUT STD_LOGIC;
    bytePlanes_plane0_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane0_full_n : IN STD_LOGIC;
    bytePlanes_plane0_write : OUT STD_LOGIC;
    bytePlanes_plane1_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    bytePlanes_plane1_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane1_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane1_full_n : IN STD_LOGIC;
    bytePlanes_plane1_write : OUT STD_LOGIC;
    Height_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    Height_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    Height_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    Height_empty_n : IN STD_LOGIC;
    Height_read : OUT STD_LOGIC;
    WidthInBytes_dout : IN STD_LOGIC_VECTOR (14 downto 0);
    WidthInBytes_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_empty_n : IN STD_LOGIC;
    WidthInBytes_read : OUT STD_LOGIC;
    VideoFormat_dout : IN STD_LOGIC_VECTOR (5 downto 0);
    VideoFormat_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    VideoFormat_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    VideoFormat_empty_n : IN STD_LOGIC;
    VideoFormat_read : OUT STD_LOGIC;
    WidthInBytes_c_din : OUT STD_LOGIC_VECTOR (14 downto 0);
    WidthInBytes_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    WidthInBytes_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    WidthInBytes_c_full_n : IN STD_LOGIC;
    WidthInBytes_c_write : OUT STD_LOGIC;
    height_c_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    height_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    height_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    height_c_full_n : IN STD_LOGIC;
    height_c_write : OUT STD_LOGIC;
    video_format_c_din : OUT STD_LOGIC_VECTOR (5 downto 0);
    video_format_c_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    video_format_c_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    video_format_c_full_n : IN STD_LOGIC;
    video_format_c_write : OUT STD_LOGIC );
end;


architecture behav of system_v_frmbuf_wr_0_0_MultiPixStream2Bytes is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal Height_blk_n : STD_LOGIC;
    signal WidthInBytes_blk_n : STD_LOGIC;
    signal VideoFormat_blk_n : STD_LOGIC;
    signal WidthInBytes_c_blk_n : STD_LOGIC;
    signal height_c_blk_n : STD_LOGIC;
    signal video_format_c_blk_n : STD_LOGIC;
    signal VideoFormat_read_read_fu_158_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal VideoFormat_read_reg_559 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal Height_read_reg_564 : STD_LOGIC_VECTOR (11 downto 0);
    signal widthInPix_reg_571 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln571_1_fu_274_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln571_1_reg_587 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln576_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln576_reg_592 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub209_fu_302_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub209_reg_597 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp11_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp11_reg_602 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp212_2_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp212_2_reg_607 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp14_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp14_reg_612 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp212_4_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp212_4_reg_617 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp212_5_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp212_5_reg_622 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp212_6_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp212_6_reg_627 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln534_1_fu_378_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln534_1_reg_639 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln539_reg_644 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub118_fu_400_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub118_reg_649 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp8_fu_416_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp8_reg_654 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp121_2_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp121_2_reg_659 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln496_1_fu_442_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln496_1_reg_671 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln501_reg_676 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub40_fu_464_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub40_reg_681 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_686 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp43_2_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp43_2_reg_691 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln583_fu_500_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln583_reg_696 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_img_read : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_write : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_write : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_img_read : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_write : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_img_read : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_write : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln583_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln546_fu_524_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln508_fu_543_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal y_2_fu_146 : STD_LOGIC_VECTOR (11 downto 0);
    signal y_8_fu_510_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal y_1_fu_150 : STD_LOGIC_VECTOR (11 downto 0);
    signal y_6_fu_529_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal y_fu_154 : STD_LOGIC_VECTOR (11 downto 0);
    signal y_4_fu_548_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_247_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln571_fu_265_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln571_fu_268_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal remainPix_4_fu_262_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln574_fu_284_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal remainPix_5_fu_294_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_308_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_330_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln534_fu_369_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln534_fu_372_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln537_fu_388_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal remainPix_3_fu_392_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_406_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln496_fu_433_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln496_fu_436_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln499_fu_452_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal remainPix_1_fu_456_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_470_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_empty_n : IN STD_LOGIC;
        img_read : OUT STD_LOGIC;
        bytePlanes_plane0_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_full_n : IN STD_LOGIC;
        bytePlanes_plane0_write : OUT STD_LOGIC;
        bytePlanes_plane1_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        bytePlanes_plane1_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane1_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane1_full_n : IN STD_LOGIC;
        bytePlanes_plane1_write : OUT STD_LOGIC;
        trunc_ln571_1 : IN STD_LOGIC_VECTOR (12 downto 0);
        VideoFormat_load : IN STD_LOGIC_VECTOR (5 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp_ln576 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp212_6 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp212_5 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp212_4 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp212_3 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp212_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        sub209_cast62 : IN STD_LOGIC_VECTOR (12 downto 0);
        cmp212_1 : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_empty_n : IN STD_LOGIC;
        img_read : OUT STD_LOGIC;
        bytePlanes_plane0_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_full_n : IN STD_LOGIC;
        bytePlanes_plane0_write : OUT STD_LOGIC;
        trunc_ln534_1 : IN STD_LOGIC_VECTOR (12 downto 0);
        icmp_ln539 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp121_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        sub118_cast59 : IN STD_LOGIC_VECTOR (12 downto 0);
        cmp121_1 : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
        img_empty_n : IN STD_LOGIC;
        img_read : OUT STD_LOGIC;
        bytePlanes_plane0_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_full_n : IN STD_LOGIC;
        bytePlanes_plane0_write : OUT STD_LOGIC;
        trunc_ln496_1 : IN STD_LOGIC_VECTOR (12 downto 0);
        icmp_ln501 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp43_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        sub40_cast56 : IN STD_LOGIC_VECTOR (12 downto 0);
        cmp43_1 : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200 : component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start,
        ap_done => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_done,
        ap_idle => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_idle,
        ap_ready => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_ready,
        img_dout => img_dout,
        img_num_data_valid => ap_const_lv2_0,
        img_fifo_cap => ap_const_lv2_0,
        img_empty_n => img_empty_n,
        img_read => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_img_read,
        bytePlanes_plane0_din => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_din,
        bytePlanes_plane0_num_data_valid => ap_const_lv11_0,
        bytePlanes_plane0_fifo_cap => ap_const_lv11_0,
        bytePlanes_plane0_full_n => bytePlanes_plane0_full_n,
        bytePlanes_plane0_write => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_write,
        bytePlanes_plane1_din => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_din,
        bytePlanes_plane1_num_data_valid => ap_const_lv11_0,
        bytePlanes_plane1_fifo_cap => ap_const_lv11_0,
        bytePlanes_plane1_full_n => bytePlanes_plane1_full_n,
        bytePlanes_plane1_write => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_write,
        trunc_ln571_1 => trunc_ln571_1_reg_587,
        VideoFormat_load => VideoFormat_read_reg_559,
        trunc_ln => trunc_ln583_reg_696,
        icmp_ln576 => icmp_ln576_reg_592,
        cmp212_6 => cmp212_6_reg_627,
        cmp212_5 => cmp212_5_reg_622,
        cmp212_4 => cmp212_4_reg_617,
        cmp212_3 => icmp14_reg_612,
        cmp212_2 => cmp212_2_reg_607,
        sub209_cast62 => sub209_reg_597,
        cmp212_1 => icmp11_reg_602);

    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221 : component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start,
        ap_done => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_done,
        ap_idle => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_idle,
        ap_ready => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_ready,
        img_dout => img_dout,
        img_num_data_valid => ap_const_lv2_0,
        img_fifo_cap => ap_const_lv2_0,
        img_empty_n => img_empty_n,
        img_read => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_img_read,
        bytePlanes_plane0_din => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_din,
        bytePlanes_plane0_num_data_valid => ap_const_lv11_0,
        bytePlanes_plane0_fifo_cap => ap_const_lv11_0,
        bytePlanes_plane0_full_n => bytePlanes_plane0_full_n,
        bytePlanes_plane0_write => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_write,
        trunc_ln534_1 => trunc_ln534_1_reg_639,
        icmp_ln539 => icmp_ln539_reg_644,
        cmp121_2 => cmp121_2_reg_659,
        sub118_cast59 => sub118_reg_649,
        cmp121_1 => icmp8_reg_654);

    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234 : component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start,
        ap_done => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_done,
        ap_idle => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_idle,
        ap_ready => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_ready,
        img_dout => img_dout,
        img_num_data_valid => ap_const_lv2_0,
        img_fifo_cap => ap_const_lv2_0,
        img_empty_n => img_empty_n,
        img_read => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_img_read,
        bytePlanes_plane0_din => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_din,
        bytePlanes_plane0_num_data_valid => ap_const_lv11_0,
        bytePlanes_plane0_fifo_cap => ap_const_lv11_0,
        bytePlanes_plane0_full_n => bytePlanes_plane0_full_n,
        bytePlanes_plane0_write => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_write,
        trunc_ln496_1 => trunc_ln496_1_reg_671,
        icmp_ln501 => icmp_ln501_reg_676,
        cmp43_2 => cmp43_2_reg_691,
        sub40_cast56 => sub40_reg_681,
        cmp43_1 => icmp_reg_686);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and ((((((icmp_ln583_fu_505_p2 = ap_const_lv1_1) and (ap_const_lv6_13 = VideoFormat_read_reg_559)) or ((icmp_ln583_fu_505_p2 = ap_const_lv1_1) and (ap_const_lv6_12 = VideoFormat_read_reg_559))) or (not((ap_const_lv6_1C = VideoFormat_read_reg_559)) and not((ap_const_lv6_13 = VideoFormat_read_reg_559)) and not((ap_const_lv6_12 = VideoFormat_read_reg_559)) and (icmp_ln508_fu_543_p2 = ap_const_lv1_1))) or ((icmp_ln546_fu_524_p2 = ap_const_lv1_1) and (ap_const_lv6_1C = VideoFormat_read_reg_559))) or (not((ap_const_lv6_C = VideoFormat_read_reg_559)) and not((ap_const_lv6_1C = VideoFormat_read_reg_559)) and not((ap_const_lv6_13 = VideoFormat_read_reg_559)) and not((ap_const_lv6_12 = VideoFormat_read_reg_559)))))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln508_fu_543_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv6_C = VideoFormat_read_reg_559))) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln546_fu_524_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv6_1C = VideoFormat_read_reg_559))) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (((icmp_ln583_fu_505_p2 = ap_const_lv1_0) and (ap_const_lv6_13 = VideoFormat_read_reg_559)) or ((icmp_ln583_fu_505_p2 = ap_const_lv1_0) and (ap_const_lv6_12 = VideoFormat_read_reg_559))))) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_1_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv6_1C = VideoFormat_read_reg_559)) then
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    y_1_fu_150 <= ap_const_lv12_0;
                elsif (((icmp_ln546_fu_524_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    y_1_fu_150 <= y_6_fu_529_p2;
                end if;
            end if; 
        end if;
    end process;

    y_2_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_const_lv6_13 = VideoFormat_read_reg_559) or (ap_const_lv6_12 = VideoFormat_read_reg_559)))) then 
                y_2_fu_146 <= ap_const_lv12_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (((icmp_ln583_fu_505_p2 = ap_const_lv1_0) and (ap_const_lv6_13 = VideoFormat_read_reg_559)) or ((icmp_ln583_fu_505_p2 = ap_const_lv1_0) and (ap_const_lv6_12 = VideoFormat_read_reg_559))))) then 
                y_2_fu_146 <= y_8_fu_510_p2;
            end if; 
        end if;
    end process;

    y_fu_154_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv6_C = VideoFormat_read_reg_559)) then
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    y_fu_154 <= ap_const_lv12_0;
                elsif (((icmp_ln508_fu_543_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    y_fu_154 <= y_4_fu_548_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                Height_read_reg_564 <= Height_dout;
                VideoFormat_read_reg_559 <= VideoFormat_dout;
                widthInPix_reg_571 <= WidthInBytes_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv6_1C = VideoFormat_read_reg_559))) then
                cmp121_2_reg_659 <= cmp121_2_fu_422_p2;
                icmp8_reg_654 <= icmp8_fu_416_p2;
                icmp_ln539_reg_644 <= grp_fu_256_p2;
                sub118_reg_649 <= sub118_fu_400_p2;
                trunc_ln534_1_reg_639 <= add_ln534_fu_372_p2(15 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_const_lv6_13 = VideoFormat_read_reg_559) or (ap_const_lv6_12 = VideoFormat_read_reg_559)))) then
                cmp212_2_reg_607 <= cmp212_2_fu_324_p2;
                cmp212_4_reg_617 <= cmp212_4_fu_346_p2;
                cmp212_5_reg_622 <= cmp212_5_fu_352_p2;
                cmp212_6_reg_627 <= cmp212_6_fu_358_p2;
                icmp11_reg_602 <= icmp11_fu_318_p2;
                icmp14_reg_612 <= icmp14_fu_340_p2;
                icmp_ln576_reg_592 <= icmp_ln576_fu_288_p2;
                sub209_reg_597 <= sub209_fu_302_p2;
                trunc_ln571_1_reg_587 <= add_ln571_fu_268_p2(15 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (ap_const_lv6_C = VideoFormat_read_reg_559))) then
                cmp43_2_reg_691 <= cmp43_2_fu_486_p2;
                icmp_ln501_reg_676 <= grp_fu_256_p2;
                icmp_reg_686 <= icmp_fu_480_p2;
                sub40_reg_681 <= sub40_fu_464_p2;
                trunc_ln496_1_reg_671 <= add_ln496_fu_436_p2(15 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((ap_const_lv6_13 = VideoFormat_read_reg_559) or (ap_const_lv6_12 = VideoFormat_read_reg_559)))) then
                trunc_ln583_reg_696 <= trunc_ln583_fu_500_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n, VideoFormat_read_read_fu_158_p2, VideoFormat_read_reg_559, ap_CS_fsm_state3, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_done, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_done, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_done, icmp_ln583_fu_505_p2, ap_CS_fsm_state4, icmp_ln546_fu_524_p2, ap_CS_fsm_state5, icmp_ln508_fu_543_p2, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not((ap_const_lv6_C = VideoFormat_read_read_fu_158_p2)) and not((ap_const_lv6_1C = VideoFormat_read_read_fu_158_p2)) and not((ap_const_lv6_13 = VideoFormat_read_read_fu_158_p2)) and not((ap_const_lv6_12 = VideoFormat_read_read_fu_158_p2)) and not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1) and ((ap_const_lv6_C = VideoFormat_read_read_fu_158_p2) or ((ap_const_lv6_1C = VideoFormat_read_read_fu_158_p2) or ((ap_const_lv6_13 = VideoFormat_read_read_fu_158_p2) or (ap_const_lv6_12 = VideoFormat_read_read_fu_158_p2)))))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((((((icmp_ln583_fu_505_p2 = ap_const_lv1_1) and (ap_const_lv6_13 = VideoFormat_read_reg_559)) or ((icmp_ln583_fu_505_p2 = ap_const_lv1_1) and (ap_const_lv6_12 = VideoFormat_read_reg_559))) or (not((ap_const_lv6_1C = VideoFormat_read_reg_559)) and not((ap_const_lv6_13 = VideoFormat_read_reg_559)) and not((ap_const_lv6_12 = VideoFormat_read_reg_559)) and (icmp_ln508_fu_543_p2 = ap_const_lv1_1))) or ((icmp_ln546_fu_524_p2 = ap_const_lv1_1) and (ap_const_lv6_1C = VideoFormat_read_reg_559))) or (not((ap_const_lv6_C = VideoFormat_read_reg_559)) and not((ap_const_lv6_1C = VideoFormat_read_reg_559)) and not((ap_const_lv6_13 = VideoFormat_read_reg_559)) and not((ap_const_lv6_12 = VideoFormat_read_reg_559)))))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((icmp_ln508_fu_543_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv6_C = VideoFormat_read_reg_559))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                elsif (((icmp_ln546_fu_524_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_lv6_1C = VideoFormat_read_reg_559))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;

    Height_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Height_blk_n <= Height_empty_n;
        else 
            Height_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    Height_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            Height_read <= ap_const_logic_1;
        else 
            Height_read <= ap_const_logic_0;
        end if; 
    end process;


    VideoFormat_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, VideoFormat_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            VideoFormat_blk_n <= VideoFormat_empty_n;
        else 
            VideoFormat_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    VideoFormat_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            VideoFormat_read <= ap_const_logic_1;
        else 
            VideoFormat_read <= ap_const_logic_0;
        end if; 
    end process;

    VideoFormat_read_read_fu_158_p2 <= VideoFormat_dout;

    WidthInBytes_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, WidthInBytes_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_blk_n <= WidthInBytes_empty_n;
        else 
            WidthInBytes_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    WidthInBytes_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, WidthInBytes_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_c_blk_n <= WidthInBytes_c_full_n;
        else 
            WidthInBytes_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    WidthInBytes_c_din <= WidthInBytes_dout;

    WidthInBytes_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_c_write <= ap_const_logic_1;
        else 
            WidthInBytes_c_write <= ap_const_logic_0;
        end if; 
    end process;


    WidthInBytes_read_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_read <= ap_const_logic_1;
        else 
            WidthInBytes_read <= ap_const_logic_0;
        end if; 
    end process;

    add_ln496_fu_436_p2 <= std_logic_vector(unsigned(zext_ln496_fu_433_p1) + unsigned(ap_const_lv16_7));
    add_ln534_fu_372_p2 <= std_logic_vector(unsigned(zext_ln534_fu_369_p1) + unsigned(ap_const_lv16_7));
    add_ln571_fu_268_p2 <= std_logic_vector(unsigned(zext_ln571_fu_265_p1) + unsigned(ap_const_lv16_7));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if (((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_done)
    begin
        if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_done)
    begin
        if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_done)
    begin
        if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
                ap_block_state1 <= ((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, VideoFormat_read_reg_559, ap_CS_fsm_state3, icmp_ln583_fu_505_p2, icmp_ln546_fu_524_p2, icmp_ln508_fu_543_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((((((icmp_ln583_fu_505_p2 = ap_const_lv1_1) and (ap_const_lv6_13 = VideoFormat_read_reg_559)) or ((icmp_ln583_fu_505_p2 = ap_const_lv1_1) and (ap_const_lv6_12 = VideoFormat_read_reg_559))) or (not((ap_const_lv6_1C = VideoFormat_read_reg_559)) and not((ap_const_lv6_13 = VideoFormat_read_reg_559)) and not((ap_const_lv6_12 = VideoFormat_read_reg_559)) and (icmp_ln508_fu_543_p2 = ap_const_lv1_1))) or ((icmp_ln546_fu_524_p2 = ap_const_lv1_1) and (ap_const_lv6_1C = VideoFormat_read_reg_559))) or (not((ap_const_lv6_C = VideoFormat_read_reg_559)) and not((ap_const_lv6_1C = VideoFormat_read_reg_559)) and not((ap_const_lv6_13 = VideoFormat_read_reg_559)) and not((ap_const_lv6_12 = VideoFormat_read_reg_559)))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(VideoFormat_read_reg_559, ap_CS_fsm_state3, icmp_ln583_fu_505_p2, icmp_ln546_fu_524_p2, icmp_ln508_fu_543_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((((((icmp_ln583_fu_505_p2 = ap_const_lv1_1) and (ap_const_lv6_13 = VideoFormat_read_reg_559)) or ((icmp_ln583_fu_505_p2 = ap_const_lv1_1) and (ap_const_lv6_12 = VideoFormat_read_reg_559))) or (not((ap_const_lv6_1C = VideoFormat_read_reg_559)) and not((ap_const_lv6_13 = VideoFormat_read_reg_559)) and not((ap_const_lv6_12 = VideoFormat_read_reg_559)) and (icmp_ln508_fu_543_p2 = ap_const_lv1_1))) or ((icmp_ln546_fu_524_p2 = ap_const_lv1_1) and (ap_const_lv6_1C = VideoFormat_read_reg_559))) or (not((ap_const_lv6_C = VideoFormat_read_reg_559)) and not((ap_const_lv6_1C = VideoFormat_read_reg_559)) and not((ap_const_lv6_13 = VideoFormat_read_reg_559)) and not((ap_const_lv6_12 = VideoFormat_read_reg_559)))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    bytePlanes_plane0_din_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_din, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_din, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_din, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            bytePlanes_plane0_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            bytePlanes_plane0_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bytePlanes_plane0_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_din;
        else 
            bytePlanes_plane0_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_din;
        end if; 
    end process;


    bytePlanes_plane0_write_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_write, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_write, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_write, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            bytePlanes_plane0_write <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_bytePlanes_plane0_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            bytePlanes_plane0_write <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_bytePlanes_plane0_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bytePlanes_plane0_write <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane0_write;
        else 
            bytePlanes_plane0_write <= ap_const_logic_0;
        end if; 
    end process;

    bytePlanes_plane1_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_din;

    bytePlanes_plane1_write_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bytePlanes_plane1_write <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_bytePlanes_plane1_write;
        else 
            bytePlanes_plane1_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp121_2_fu_422_p2 <= "1" when (unsigned(remainPix_3_fu_392_p3) > unsigned(ap_const_lv3_2)) else "0";
    cmp212_2_fu_324_p2 <= "1" when (unsigned(remainPix_5_fu_294_p3) > unsigned(ap_const_lv4_2)) else "0";
    cmp212_4_fu_346_p2 <= "1" when (unsigned(remainPix_5_fu_294_p3) > unsigned(ap_const_lv4_4)) else "0";
    cmp212_5_fu_352_p2 <= "1" when (unsigned(remainPix_5_fu_294_p3) > unsigned(ap_const_lv4_5)) else "0";
    cmp212_6_fu_358_p2 <= "1" when (unsigned(remainPix_5_fu_294_p3) > unsigned(ap_const_lv4_6)) else "0";
    cmp43_2_fu_486_p2 <= "1" when (unsigned(remainPix_1_fu_456_p3) > unsigned(ap_const_lv3_2)) else "0";
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_ap_start_reg;
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_ap_start_reg;
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_ap_start_reg;
    grp_fu_247_p4 <= widthInPix_reg_571(2 downto 1);
    grp_fu_256_p2 <= "1" when (grp_fu_247_p4 = ap_const_lv2_0) else "0";

    height_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_c_blk_n <= height_c_full_n;
        else 
            height_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_c_din <= Height_dout;

    height_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_c_write <= ap_const_logic_1;
        else 
            height_c_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp11_fu_318_p2 <= "0" when (tmp_2_fu_308_p4 = ap_const_lv3_0) else "1";
    icmp14_fu_340_p2 <= "0" when (tmp_3_fu_330_p4 = ap_const_lv2_0) else "1";
    icmp8_fu_416_p2 <= "0" when (tmp_1_fu_406_p4 = ap_const_lv2_0) else "1";
    icmp_fu_480_p2 <= "0" when (tmp_fu_470_p4 = ap_const_lv2_0) else "1";
    icmp_ln508_fu_543_p2 <= "1" when (y_fu_154 = Height_read_reg_564) else "0";
    icmp_ln546_fu_524_p2 <= "1" when (y_1_fu_150 = Height_read_reg_564) else "0";
    icmp_ln576_fu_288_p2 <= "1" when (remainPix_4_fu_262_p1 = ap_const_lv3_0) else "0";
    icmp_ln583_fu_505_p2 <= "1" when (y_2_fu_146 = Height_read_reg_564) else "0";

    img_read_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_img_read, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_img_read, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_img_read, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            img_read <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_1_fu_234_img_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            img_read <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_549_5_fu_221_img_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            img_read <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8_fu_200_img_read;
        else 
            img_read <= ap_const_logic_0;
        end if; 
    end process;

    remainPix_1_fu_456_p3 <= 
        ap_const_lv3_4 when (grp_fu_256_p2(0) = '1') else 
        zext_ln499_fu_452_p1;
    remainPix_3_fu_392_p3 <= 
        ap_const_lv3_4 when (grp_fu_256_p2(0) = '1') else 
        zext_ln537_fu_388_p1;
    remainPix_4_fu_262_p1 <= widthInPix_reg_571(3 - 1 downto 0);
    remainPix_5_fu_294_p3 <= 
        ap_const_lv4_8 when (icmp_ln576_fu_288_p2(0) = '1') else 
        zext_ln574_fu_284_p1;
    sub118_fu_400_p2 <= std_logic_vector(unsigned(trunc_ln534_1_fu_378_p4) + unsigned(ap_const_lv13_1FFF));
    sub209_fu_302_p2 <= std_logic_vector(unsigned(trunc_ln571_1_fu_274_p4) + unsigned(ap_const_lv13_1FFF));
    sub40_fu_464_p2 <= std_logic_vector(unsigned(trunc_ln496_1_fu_442_p4) + unsigned(ap_const_lv13_1FFF));
    tmp_1_fu_406_p4 <= remainPix_3_fu_392_p3(2 downto 1);
    tmp_2_fu_308_p4 <= remainPix_5_fu_294_p3(3 downto 1);
    tmp_3_fu_330_p4 <= remainPix_5_fu_294_p3(3 downto 2);
    tmp_fu_470_p4 <= remainPix_1_fu_456_p3(2 downto 1);
    trunc_ln496_1_fu_442_p4 <= add_ln496_fu_436_p2(15 downto 3);
    trunc_ln534_1_fu_378_p4 <= add_ln534_fu_372_p2(15 downto 3);
    trunc_ln571_1_fu_274_p4 <= add_ln571_fu_268_p2(15 downto 3);
    trunc_ln583_fu_500_p1 <= y_2_fu_146(1 - 1 downto 0);

    video_format_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, video_format_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            video_format_c_blk_n <= video_format_c_full_n;
        else 
            video_format_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    video_format_c_din <= VideoFormat_dout;

    video_format_c_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, Height_empty_n, WidthInBytes_empty_n, VideoFormat_empty_n, WidthInBytes_c_full_n, height_c_full_n, video_format_c_full_n)
    begin
        if ((not(((video_format_c_full_n = ap_const_logic_0) or (height_c_full_n = ap_const_logic_0) or (ap_const_logic_0 = WidthInBytes_c_full_n) or (ap_const_logic_0 = VideoFormat_empty_n) or (ap_const_logic_0 = WidthInBytes_empty_n) or (ap_const_logic_0 = Height_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            video_format_c_write <= ap_const_logic_1;
        else 
            video_format_c_write <= ap_const_logic_0;
        end if; 
    end process;

    y_4_fu_548_p2 <= std_logic_vector(unsigned(y_fu_154) + unsigned(ap_const_lv12_1));
    y_6_fu_529_p2 <= std_logic_vector(unsigned(y_1_fu_150) + unsigned(ap_const_lv12_1));
    y_8_fu_510_p2 <= std_logic_vector(unsigned(y_2_fu_146) + unsigned(ap_const_lv12_1));
    zext_ln496_fu_433_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(widthInPix_reg_571),16));
    zext_ln499_fu_452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_247_p4),3));
    zext_ln534_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(widthInPix_reg_571),16));
    zext_ln537_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_247_p4),3));
    zext_ln571_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(widthInPix_reg_571),16));
    zext_ln574_fu_284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(remainPix_4_fu_262_p1),4));
end behav;
