-- ==============================================================
-- Generated by Vitis HLS v2023.2.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity system_v_frmbuf_wr_0_0_MultiPixStream2Bytes is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    img_empty_n : IN STD_LOGIC;
    img_read : OUT STD_LOGIC;
    bytePlanes_plane0_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane0_full_n : IN STD_LOGIC;
    bytePlanes_plane0_write : OUT STD_LOGIC;
    bytePlanes_plane1_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    bytePlanes_plane1_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane1_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane1_full_n : IN STD_LOGIC;
    bytePlanes_plane1_write : OUT STD_LOGIC;
    Height_val : IN STD_LOGIC_VECTOR (11 downto 0);
    WidthInBytes_val_dout : IN STD_LOGIC_VECTOR (14 downto 0);
    WidthInBytes_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_val_empty_n : IN STD_LOGIC;
    WidthInBytes_val_read : OUT STD_LOGIC;
    VideoFormat_val : IN STD_LOGIC_VECTOR (5 downto 0);
    WidthInBytes_val2_c_din : OUT STD_LOGIC_VECTOR (14 downto 0);
    WidthInBytes_val2_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_val2_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    WidthInBytes_val2_c_full_n : IN STD_LOGIC;
    WidthInBytes_val2_c_write : OUT STD_LOGIC );
end;


architecture behav of system_v_frmbuf_wr_0_0_MultiPixStream2Bytes is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv6_12 : STD_LOGIC_VECTOR (5 downto 0) := "010010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";
    constant ap_const_lv6_1C : STD_LOGIC_VECTOR (5 downto 0) := "011100";
    constant ap_const_lv6_C : STD_LOGIC_VECTOR (5 downto 0) := "001100";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv16_7 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv13_1FFF : STD_LOGIC_VECTOR (12 downto 0) := "1111111111111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv6_F : STD_LOGIC_VECTOR (5 downto 0) := "001111";
    constant ap_const_lv6_10 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_const_lv6_1B : STD_LOGIC_VECTOR (5 downto 0) := "011011";
    constant ap_const_lv6_A : STD_LOGIC_VECTOR (5 downto 0) := "001010";
    constant ap_const_lv6_B : STD_LOGIC_VECTOR (5 downto 0) := "001011";
    constant ap_const_lv6_29 : STD_LOGIC_VECTOR (5 downto 0) := "101001";
    constant ap_const_lv6_2A : STD_LOGIC_VECTOR (5 downto 0) := "101010";
    constant ap_const_lv6_2B : STD_LOGIC_VECTOR (5 downto 0) := "101011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal WidthInBytes_val_blk_n : STD_LOGIC;
    signal WidthInBytes_val2_c_blk_n : STD_LOGIC;
    signal widthInPix_reg_617 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal VideoFormat_val_read_read_fu_196_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln741_2_fu_297_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln741_2_reg_657 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln745_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln745_reg_662 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub213_fu_325_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub213_reg_667 : STD_LOGIC_VECTOR (12 downto 0);
    signal cmp216_fu_331_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp216_reg_672 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp13_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp13_reg_677 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp216_2_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp216_2_reg_682 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp16_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp16_reg_687 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp216_4_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp216_4_reg_692 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp216_5_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp216_5_reg_697 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp216_6_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp216_6_reg_702 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln700_2_fu_407_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln700_2_reg_726 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_279_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln704_reg_731 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub122_fu_429_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub122_reg_736 : STD_LOGIC_VECTOR (12 downto 0);
    signal cmp125_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp125_reg_741 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp10_fu_451_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp10_reg_746 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp125_2_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp125_2_reg_751 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln658_2_fu_477_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal trunc_ln658_2_reg_775 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp_ln662_reg_780 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub44_fu_499_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sub44_reg_785 : STD_LOGIC_VECTOR (12 downto 0);
    signal cmp47_fu_505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp47_reg_790 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_795 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp47_2_fu_527_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp47_2_reg_800 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_lcssa127141_load_reg_808 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal p_lcssa128144_load_reg_813 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln753_fu_558_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln753_reg_818 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_lcssa109119_load_reg_826 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa110122_load_reg_831 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa92101_load_reg_839 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa93104_load_reg_844 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_img_read : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_write : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_write : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_img_read : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_write : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_img_read : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_din : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_write : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal p_lcssa128144_fu_154 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa127141_fu_150 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal p_lcssa110122_fu_166 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa109119_fu_162 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal p_lcssa93104_fu_178 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa92101_fu_174 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_2_fu_146 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal y_8_fu_546_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln753_fu_541_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_1_fu_158 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal y_6_fu_575_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln712_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_fu_170 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal y_4_fu_600_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal icmp_ln670_fu_595_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_270_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln741_fu_288_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln741_fu_291_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal remainPix_4_fu_285_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln743_fu_307_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal remainPix_5_fu_317_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_2_fu_337_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_3_fu_359_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln700_fu_398_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln700_fu_401_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln702_fu_417_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal remainPix_3_fu_421_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_1_fu_441_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln658_fu_468_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln658_fu_471_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln660_fu_487_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal remainPix_1_fu_491_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_511_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        img_empty_n : IN STD_LOGIC;
        img_read : OUT STD_LOGIC;
        p_lcssa128144 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_lcssa127141 : IN STD_LOGIC_VECTOR (7 downto 0);
        trunc_ln741_2 : IN STD_LOGIC_VECTOR (12 downto 0);
        bytePlanes_plane1_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        bytePlanes_plane1_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane1_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane1_full_n : IN STD_LOGIC;
        bytePlanes_plane1_write : OUT STD_LOGIC;
        bytePlanes_plane0_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_full_n : IN STD_LOGIC;
        bytePlanes_plane0_write : OUT STD_LOGIC;
        VideoFormat_val : IN STD_LOGIC_VECTOR (5 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp_ln745 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp216_6 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp216_5 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp216_4 : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp16 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp216_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp13 : IN STD_LOGIC_VECTOR (0 downto 0);
        sub213_cast58 : IN STD_LOGIC_VECTOR (12 downto 0);
        cmp216 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC );
    end component;


    component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        img_empty_n : IN STD_LOGIC;
        img_read : OUT STD_LOGIC;
        p_lcssa110122 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_lcssa109119 : IN STD_LOGIC_VECTOR (7 downto 0);
        trunc_ln700_2 : IN STD_LOGIC_VECTOR (12 downto 0);
        bytePlanes_plane0_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_full_n : IN STD_LOGIC;
        bytePlanes_plane0_write : OUT STD_LOGIC;
        icmp_ln704 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp125_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp10 : IN STD_LOGIC_VECTOR (0 downto 0);
        sub122_cast57 : IN STD_LOGIC_VECTOR (12 downto 0);
        cmp125 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC );
    end component;


    component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        img_empty_n : IN STD_LOGIC;
        img_read : OUT STD_LOGIC;
        p_lcssa93104 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_lcssa92101 : IN STD_LOGIC_VECTOR (7 downto 0);
        trunc_ln658_2 : IN STD_LOGIC_VECTOR (12 downto 0);
        bytePlanes_plane0_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
        bytePlanes_plane0_full_n : IN STD_LOGIC;
        bytePlanes_plane0_write : OUT STD_LOGIC;
        icmp_ln662 : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp47_2 : IN STD_LOGIC_VECTOR (0 downto 0);
        icmp : IN STD_LOGIC_VECTOR (0 downto 0);
        sub44_cast56 : IN STD_LOGIC_VECTOR (12 downto 0);
        cmp47 : IN STD_LOGIC_VECTOR (0 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208 : component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start,
        ap_done => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_done,
        ap_idle => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_idle,
        ap_ready => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_ready,
        img_dout => img_dout,
        img_num_data_valid => ap_const_lv3_0,
        img_fifo_cap => ap_const_lv3_0,
        img_empty_n => img_empty_n,
        img_read => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_img_read,
        p_lcssa128144 => p_lcssa128144_load_reg_813,
        p_lcssa127141 => p_lcssa127141_load_reg_808,
        trunc_ln741_2 => trunc_ln741_2_reg_657,
        bytePlanes_plane1_din => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_din,
        bytePlanes_plane1_num_data_valid => ap_const_lv11_0,
        bytePlanes_plane1_fifo_cap => ap_const_lv11_0,
        bytePlanes_plane1_full_n => bytePlanes_plane1_full_n,
        bytePlanes_plane1_write => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_write,
        bytePlanes_plane0_din => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_din,
        bytePlanes_plane0_num_data_valid => ap_const_lv11_0,
        bytePlanes_plane0_fifo_cap => ap_const_lv11_0,
        bytePlanes_plane0_full_n => bytePlanes_plane0_full_n,
        bytePlanes_plane0_write => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_write,
        VideoFormat_val => VideoFormat_val,
        empty => trunc_ln753_reg_818,
        icmp_ln745 => icmp_ln745_reg_662,
        cmp216_6 => cmp216_6_reg_702,
        cmp216_5 => cmp216_5_reg_697,
        cmp216_4 => cmp216_4_reg_692,
        icmp16 => icmp16_reg_687,
        cmp216_2 => cmp216_2_reg_682,
        icmp13 => icmp13_reg_677,
        sub213_cast58 => sub213_reg_667,
        cmp216 => cmp216_reg_672,
        p_out => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out,
        p_out_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out_ap_vld,
        p_out1 => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1,
        p_out1_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1_ap_vld);

    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234 : component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start,
        ap_done => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_done,
        ap_idle => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_idle,
        ap_ready => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_ready,
        img_dout => img_dout,
        img_num_data_valid => ap_const_lv3_0,
        img_fifo_cap => ap_const_lv3_0,
        img_empty_n => img_empty_n,
        img_read => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_img_read,
        p_lcssa110122 => p_lcssa110122_load_reg_831,
        p_lcssa109119 => p_lcssa109119_load_reg_826,
        trunc_ln700_2 => trunc_ln700_2_reg_726,
        bytePlanes_plane0_din => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_din,
        bytePlanes_plane0_num_data_valid => ap_const_lv11_0,
        bytePlanes_plane0_fifo_cap => ap_const_lv11_0,
        bytePlanes_plane0_full_n => bytePlanes_plane0_full_n,
        bytePlanes_plane0_write => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_write,
        icmp_ln704 => icmp_ln704_reg_731,
        cmp125_2 => cmp125_2_reg_751,
        icmp10 => icmp10_reg_746,
        sub122_cast57 => sub122_reg_736,
        cmp125 => cmp125_reg_741,
        p_out => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out,
        p_out_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out_ap_vld,
        p_out1 => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1,
        p_out1_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1_ap_vld);

    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252 : component system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start,
        ap_done => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_done,
        ap_idle => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_idle,
        ap_ready => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_ready,
        img_dout => img_dout,
        img_num_data_valid => ap_const_lv3_0,
        img_fifo_cap => ap_const_lv3_0,
        img_empty_n => img_empty_n,
        img_read => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_img_read,
        p_lcssa93104 => p_lcssa93104_load_reg_844,
        p_lcssa92101 => p_lcssa92101_load_reg_839,
        trunc_ln658_2 => trunc_ln658_2_reg_775,
        bytePlanes_plane0_din => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_din,
        bytePlanes_plane0_num_data_valid => ap_const_lv11_0,
        bytePlanes_plane0_fifo_cap => ap_const_lv11_0,
        bytePlanes_plane0_full_n => bytePlanes_plane0_full_n,
        bytePlanes_plane0_write => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_write,
        icmp_ln662 => icmp_ln662_reg_780,
        cmp47_2 => cmp47_2_reg_800,
        icmp => icmp_reg_795,
        sub44_cast56 => sub44_reg_785,
        cmp47 => cmp47_reg_790,
        p_out => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out,
        p_out_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out_ap_vld,
        p_out1 => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1,
        p_out1_ap_vld => grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and ((ap_const_lv6_2B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_2A = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_29 = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_A = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_1B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_10 = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_F = VideoFormat_val_read_read_fu_196_p2) or ((((not((ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_13 = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_12 = VideoFormat_val_read_read_fu_196_p2))) or (not((ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2)) and (icmp_ln753_fu_541_p2 = ap_const_lv1_1))) or ((icmp_ln712_fu_570_p2 = ap_const_lv1_1) and (ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2))) 
    or ((icmp_ln670_fu_595_p2 = ap_const_lv1_1) and (ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2))))))))))))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_1_fu_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2)) then
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    y_1_fu_158 <= ap_const_lv12_0;
                elsif (((icmp_ln712_fu_570_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    y_1_fu_158 <= y_6_fu_575_p2;
                end if;
            end if; 
        end if;
    end process;

    y_2_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and ((ap_const_lv6_13 = VideoFormat_val_read_read_fu_196_p2) or (ap_const_lv6_12 = VideoFormat_val_read_read_fu_196_p2)))) then 
                y_2_fu_146 <= ap_const_lv12_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (((ap_const_lv6_13 = VideoFormat_val_read_read_fu_196_p2) and (icmp_ln753_fu_541_p2 = ap_const_lv1_0)) or ((icmp_ln753_fu_541_p2 = ap_const_lv1_0) and (ap_const_lv6_12 = VideoFormat_val_read_read_fu_196_p2))))) then 
                y_2_fu_146 <= y_8_fu_546_p2;
            end if; 
        end if;
    end process;

    y_fu_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2)) then
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    y_fu_170 <= ap_const_lv12_0;
                elsif (((icmp_ln670_fu_595_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    y_fu_170 <= y_4_fu_600_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                cmp125_2_reg_751 <= cmp125_2_fu_457_p2;
                cmp125_reg_741 <= cmp125_fu_435_p2;
                cmp216_2_reg_682 <= cmp216_2_fu_353_p2;
                cmp216_4_reg_692 <= cmp216_4_fu_375_p2;
                cmp216_5_reg_697 <= cmp216_5_fu_381_p2;
                cmp216_6_reg_702 <= cmp216_6_fu_387_p2;
                cmp216_reg_672 <= cmp216_fu_331_p2;
                cmp47_2_reg_800 <= cmp47_2_fu_527_p2;
                cmp47_reg_790 <= cmp47_fu_505_p2;
                icmp10_reg_746 <= icmp10_fu_451_p2;
                icmp13_reg_677 <= icmp13_fu_347_p2;
                icmp16_reg_687 <= icmp16_fu_369_p2;
                icmp_ln662_reg_780 <= grp_fu_279_p2;
                icmp_ln704_reg_731 <= grp_fu_279_p2;
                icmp_ln745_reg_662 <= icmp_ln745_fu_311_p2;
                icmp_reg_795 <= icmp_fu_521_p2;
                sub122_reg_736 <= sub122_fu_429_p2;
                sub213_reg_667 <= sub213_fu_325_p2;
                sub44_reg_785 <= sub44_fu_499_p2;
                trunc_ln658_2_reg_775 <= add_ln658_fu_471_p2(15 downto 3);
                trunc_ln700_2_reg_726 <= add_ln700_fu_401_p2(15 downto 3);
                trunc_ln741_2_reg_657 <= add_ln741_fu_291_p2(15 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                p_lcssa109119_fu_162 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                p_lcssa109119_load_reg_826 <= p_lcssa109119_fu_162;
                p_lcssa110122_load_reg_831 <= p_lcssa110122_fu_166;
                p_lcssa127141_load_reg_808 <= p_lcssa127141_fu_150;
                p_lcssa128144_load_reg_813 <= p_lcssa128144_fu_154;
                p_lcssa92101_load_reg_839 <= p_lcssa92101_fu_174;
                p_lcssa93104_load_reg_844 <= p_lcssa93104_fu_178;
                trunc_ln753_reg_818 <= trunc_ln753_fu_558_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                p_lcssa110122_fu_166 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1_ap_vld = ap_const_logic_1))) then
                p_lcssa127141_fu_150 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out_ap_vld = ap_const_logic_1))) then
                p_lcssa128144_fu_154 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                p_lcssa92101_fu_174 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                p_lcssa93104_fu_178 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                widthInPix_reg_617 <= WidthInBytes_val_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, VideoFormat_val_read_read_fu_196_p2, ap_CS_fsm_state3, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_done, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_done, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_done, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9, icmp_ln753_fu_541_p2, icmp_ln712_fu_570_p2, icmp_ln670_fu_595_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((ap_const_lv6_2B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_2A = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_29 = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_A = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_1B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_10 = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_F = VideoFormat_val_read_read_fu_196_p2) or ((((not((ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_13 = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_12 = VideoFormat_val_read_read_fu_196_p2))) or (not((ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2)) and (icmp_ln753_fu_541_p2 = ap_const_lv1_1))) or ((icmp_ln712_fu_570_p2 = ap_const_lv1_1) and (ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2))) 
    or ((icmp_ln670_fu_595_p2 = ap_const_lv1_1) and (ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2))))))))))))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((icmp_ln670_fu_595_p2 = ap_const_lv1_0) and (ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                elsif (((icmp_ln712_fu_570_p2 = ap_const_lv1_0) and (ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    VideoFormat_val_read_read_fu_196_p2 <= VideoFormat_val;

    WidthInBytes_val2_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, WidthInBytes_val2_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_val2_c_blk_n <= WidthInBytes_val2_c_full_n;
        else 
            WidthInBytes_val2_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    WidthInBytes_val2_c_din <= WidthInBytes_val_dout;

    WidthInBytes_val2_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_val2_c_write <= ap_const_logic_1;
        else 
            WidthInBytes_val2_c_write <= ap_const_logic_0;
        end if; 
    end process;


    WidthInBytes_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, WidthInBytes_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_val_blk_n <= WidthInBytes_val_empty_n;
        else 
            WidthInBytes_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    WidthInBytes_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            WidthInBytes_val_read <= ap_const_logic_1;
        else 
            WidthInBytes_val_read <= ap_const_logic_0;
        end if; 
    end process;

    add_ln658_fu_471_p2 <= std_logic_vector(unsigned(zext_ln658_fu_468_p1) + unsigned(ap_const_lv16_7));
    add_ln700_fu_401_p2 <= std_logic_vector(unsigned(zext_ln700_fu_398_p1) + unsigned(ap_const_lv16_7));
    add_ln741_fu_291_p2 <= std_logic_vector(unsigned(zext_ln741_fu_288_p1) + unsigned(ap_const_lv16_7));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_done)
    begin
        if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_done)
    begin
        if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_done)
    begin
        if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, WidthInBytes_val_empty_n, WidthInBytes_val2_c_full_n)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = WidthInBytes_val2_c_full_n) or (ap_const_logic_0 = WidthInBytes_val_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, VideoFormat_val_read_read_fu_196_p2, ap_CS_fsm_state3, icmp_ln753_fu_541_p2, icmp_ln712_fu_570_p2, icmp_ln670_fu_595_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((ap_const_lv6_2B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_2A = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_29 = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_A = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_1B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_10 = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_F = VideoFormat_val_read_read_fu_196_p2) or ((((not((ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_13 = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_12 = VideoFormat_val_read_read_fu_196_p2))) or (not((ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2)) and (icmp_ln753_fu_541_p2 = ap_const_lv1_1))) or ((icmp_ln712_fu_570_p2 = ap_const_lv1_1) and (ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2))) 
    or ((icmp_ln670_fu_595_p2 = ap_const_lv1_1) and (ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2))))))))))))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(VideoFormat_val_read_read_fu_196_p2, ap_CS_fsm_state3, icmp_ln753_fu_541_p2, icmp_ln712_fu_570_p2, icmp_ln670_fu_595_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and ((ap_const_lv6_2B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_2A = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_29 = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_A = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_1B = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_10 = VideoFormat_val_read_read_fu_196_p2) or ((ap_const_lv6_F = VideoFormat_val_read_read_fu_196_p2) or ((((not((ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_13 = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_12 = VideoFormat_val_read_read_fu_196_p2))) or (not((ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2)) and not((ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2)) and (icmp_ln753_fu_541_p2 = ap_const_lv1_1))) or ((icmp_ln712_fu_570_p2 = ap_const_lv1_1) and (ap_const_lv6_1C = VideoFormat_val_read_read_fu_196_p2))) 
    or ((icmp_ln670_fu_595_p2 = ap_const_lv1_1) and (ap_const_lv6_C = VideoFormat_val_read_read_fu_196_p2))))))))))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    bytePlanes_plane0_din_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_din, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_din, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_din, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            bytePlanes_plane0_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            bytePlanes_plane0_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_din;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            bytePlanes_plane0_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_din;
        else 
            bytePlanes_plane0_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_din;
        end if; 
    end process;


    bytePlanes_plane0_write_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_write, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_write, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_write, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            bytePlanes_plane0_write <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            bytePlanes_plane0_write <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_write;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            bytePlanes_plane0_write <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_write;
        else 
            bytePlanes_plane0_write <= ap_const_logic_0;
        end if; 
    end process;

    bytePlanes_plane1_din <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_din;

    bytePlanes_plane1_write_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_write, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            bytePlanes_plane1_write <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_write;
        else 
            bytePlanes_plane1_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp125_2_fu_457_p2 <= "1" when (unsigned(remainPix_3_fu_421_p3) > unsigned(ap_const_lv3_2)) else "0";
    cmp125_fu_435_p2 <= "0" when (remainPix_3_fu_421_p3 = ap_const_lv3_0) else "1";
    cmp216_2_fu_353_p2 <= "1" when (unsigned(remainPix_5_fu_317_p3) > unsigned(ap_const_lv4_2)) else "0";
    cmp216_4_fu_375_p2 <= "1" when (unsigned(remainPix_5_fu_317_p3) > unsigned(ap_const_lv4_4)) else "0";
    cmp216_5_fu_381_p2 <= "1" when (unsigned(remainPix_5_fu_317_p3) > unsigned(ap_const_lv4_5)) else "0";
    cmp216_6_fu_387_p2 <= "1" when (unsigned(remainPix_5_fu_317_p3) > unsigned(ap_const_lv4_6)) else "0";
    cmp216_fu_331_p2 <= "0" when (remainPix_5_fu_317_p3 = ap_const_lv4_0) else "1";
    cmp47_2_fu_527_p2 <= "1" when (unsigned(remainPix_1_fu_491_p3) > unsigned(ap_const_lv3_2)) else "0";
    cmp47_fu_505_p2 <= "0" when (remainPix_1_fu_491_p3 = ap_const_lv3_0) else "1";
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg;
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg;
    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg;
    grp_fu_270_p4 <= widthInPix_reg_617(2 downto 1);
    grp_fu_279_p2 <= "1" when (grp_fu_270_p4 = ap_const_lv2_0) else "0";
    icmp10_fu_451_p2 <= "0" when (tmp_1_fu_441_p4 = ap_const_lv2_0) else "1";
    icmp13_fu_347_p2 <= "0" when (tmp_2_fu_337_p4 = ap_const_lv3_0) else "1";
    icmp16_fu_369_p2 <= "0" when (tmp_3_fu_359_p4 = ap_const_lv2_0) else "1";
    icmp_fu_521_p2 <= "0" when (tmp_fu_511_p4 = ap_const_lv2_0) else "1";
    icmp_ln670_fu_595_p2 <= "1" when (y_fu_170 = Height_val) else "0";
    icmp_ln712_fu_570_p2 <= "1" when (y_1_fu_158 = Height_val) else "0";
    icmp_ln745_fu_311_p2 <= "1" when (remainPix_4_fu_285_p1 = ap_const_lv3_0) else "0";
    icmp_ln753_fu_541_p2 <= "1" when (y_2_fu_146 = Height_val) else "0";

    img_read_assign_proc : process(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_img_read, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_img_read, grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_img_read, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            img_read <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_img_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            img_read <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_img_read;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            img_read <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_img_read;
        else 
            img_read <= ap_const_logic_0;
        end if; 
    end process;

    remainPix_1_fu_491_p3 <= 
        ap_const_lv3_4 when (grp_fu_279_p2(0) = '1') else 
        zext_ln660_fu_487_p1;
    remainPix_3_fu_421_p3 <= 
        ap_const_lv3_4 when (grp_fu_279_p2(0) = '1') else 
        zext_ln702_fu_417_p1;
    remainPix_4_fu_285_p1 <= widthInPix_reg_617(3 - 1 downto 0);
    remainPix_5_fu_317_p3 <= 
        ap_const_lv4_8 when (icmp_ln745_fu_311_p2(0) = '1') else 
        zext_ln743_fu_307_p1;
    sub122_fu_429_p2 <= std_logic_vector(unsigned(trunc_ln700_2_fu_407_p4) + unsigned(ap_const_lv13_1FFF));
    sub213_fu_325_p2 <= std_logic_vector(unsigned(trunc_ln741_2_fu_297_p4) + unsigned(ap_const_lv13_1FFF));
    sub44_fu_499_p2 <= std_logic_vector(unsigned(trunc_ln658_2_fu_477_p4) + unsigned(ap_const_lv13_1FFF));
    tmp_1_fu_441_p4 <= remainPix_3_fu_421_p3(2 downto 1);
    tmp_2_fu_337_p4 <= remainPix_5_fu_317_p3(3 downto 1);
    tmp_3_fu_359_p4 <= remainPix_5_fu_317_p3(3 downto 2);
    tmp_fu_511_p4 <= remainPix_1_fu_491_p3(2 downto 1);
    trunc_ln658_2_fu_477_p4 <= add_ln658_fu_471_p2(15 downto 3);
    trunc_ln700_2_fu_407_p4 <= add_ln700_fu_401_p2(15 downto 3);
    trunc_ln741_2_fu_297_p4 <= add_ln741_fu_291_p2(15 downto 3);
    trunc_ln753_fu_558_p1 <= y_2_fu_146(1 - 1 downto 0);
    y_4_fu_600_p2 <= std_logic_vector(unsigned(y_fu_170) + unsigned(ap_const_lv12_1));
    y_6_fu_575_p2 <= std_logic_vector(unsigned(y_1_fu_158) + unsigned(ap_const_lv12_1));
    y_8_fu_546_p2 <= std_logic_vector(unsigned(y_2_fu_146) + unsigned(ap_const_lv12_1));
    zext_ln658_fu_468_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(widthInPix_reg_617),16));
    zext_ln660_fu_487_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_270_p4),3));
    zext_ln700_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(widthInPix_reg_617),16));
    zext_ln702_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_270_p4),3));
    zext_ln741_fu_288_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(widthInPix_reg_617),16));
    zext_ln743_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(remainPix_4_fu_285_p1),4));
end behav;
