# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.srcs/sources_1/bd/system/ip/system_axis_subset_converter_in_0/system_axis_subset_converter_in_0.xci
# IP: The module: 'system_axis_subset_converter_in_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.gen/sources_1/bd/system/ip/system_axis_subset_converter_in_0/system_axis_subset_converter_in_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_subset_converter_in_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.srcs/sources_1/bd/system/ip/system_axis_subset_converter_in_0/system_axis_subset_converter_in_0.xci
# IP: The module: 'system_axis_subset_converter_in_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.gen/sources_1/bd/system/ip/system_axis_subset_converter_in_0/system_axis_subset_converter_in_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_subset_converter_in_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
