// ==============================================================
// Generated by Vitis HLS v2023.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module system_v_frmbuf_wr_0_0_MultiPixStream2Bytes (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_dout,
        img_num_data_valid,
        img_fifo_cap,
        img_empty_n,
        img_read,
        bytePlanes_plane0_din,
        bytePlanes_plane0_num_data_valid,
        bytePlanes_plane0_fifo_cap,
        bytePlanes_plane0_full_n,
        bytePlanes_plane0_write,
        bytePlanes_plane1_din,
        bytePlanes_plane1_num_data_valid,
        bytePlanes_plane1_fifo_cap,
        bytePlanes_plane1_full_n,
        bytePlanes_plane1_write,
        Height_val,
        WidthInBytes_val_dout,
        WidthInBytes_val_num_data_valid,
        WidthInBytes_val_fifo_cap,
        WidthInBytes_val_empty_n,
        WidthInBytes_val_read,
        VideoFormat_val,
        WidthInBytes_val2_c_din,
        WidthInBytes_val2_c_num_data_valid,
        WidthInBytes_val2_c_fifo_cap,
        WidthInBytes_val2_c_full_n,
        WidthInBytes_val2_c_write
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] img_dout;
input  [2:0] img_num_data_valid;
input  [2:0] img_fifo_cap;
input   img_empty_n;
output   img_read;
output  [63:0] bytePlanes_plane0_din;
input  [10:0] bytePlanes_plane0_num_data_valid;
input  [10:0] bytePlanes_plane0_fifo_cap;
input   bytePlanes_plane0_full_n;
output   bytePlanes_plane0_write;
output  [63:0] bytePlanes_plane1_din;
input  [10:0] bytePlanes_plane1_num_data_valid;
input  [10:0] bytePlanes_plane1_fifo_cap;
input   bytePlanes_plane1_full_n;
output   bytePlanes_plane1_write;
input  [11:0] Height_val;
input  [14:0] WidthInBytes_val_dout;
input  [2:0] WidthInBytes_val_num_data_valid;
input  [2:0] WidthInBytes_val_fifo_cap;
input   WidthInBytes_val_empty_n;
output   WidthInBytes_val_read;
input  [5:0] VideoFormat_val;
output  [14:0] WidthInBytes_val2_c_din;
input  [2:0] WidthInBytes_val2_c_num_data_valid;
input  [2:0] WidthInBytes_val2_c_fifo_cap;
input   WidthInBytes_val2_c_full_n;
output   WidthInBytes_val2_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_read;
reg[63:0] bytePlanes_plane0_din;
reg bytePlanes_plane0_write;
reg bytePlanes_plane1_write;
reg WidthInBytes_val_read;
reg WidthInBytes_val2_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    WidthInBytes_val_blk_n;
reg    WidthInBytes_val2_c_blk_n;
reg   [14:0] widthInPix_reg_617;
reg    ap_block_state1;
wire   [5:0] VideoFormat_val_read_read_fu_196_p2;
wire    ap_CS_fsm_state2;
wire   [12:0] trunc_ln741_2_fu_297_p4;
reg   [12:0] trunc_ln741_2_reg_657;
wire   [0:0] icmp_ln745_fu_311_p2;
reg   [0:0] icmp_ln745_reg_662;
wire   [12:0] sub213_fu_325_p2;
reg   [12:0] sub213_reg_667;
wire   [0:0] cmp216_fu_331_p2;
reg   [0:0] cmp216_reg_672;
wire   [0:0] icmp13_fu_347_p2;
reg   [0:0] icmp13_reg_677;
wire   [0:0] cmp216_2_fu_353_p2;
reg   [0:0] cmp216_2_reg_682;
wire   [0:0] icmp16_fu_369_p2;
reg   [0:0] icmp16_reg_687;
wire   [0:0] cmp216_4_fu_375_p2;
reg   [0:0] cmp216_4_reg_692;
wire   [0:0] cmp216_5_fu_381_p2;
reg   [0:0] cmp216_5_reg_697;
wire   [0:0] cmp216_6_fu_387_p2;
reg   [0:0] cmp216_6_reg_702;
wire   [12:0] trunc_ln700_2_fu_407_p4;
reg   [12:0] trunc_ln700_2_reg_726;
wire   [0:0] grp_fu_279_p2;
reg   [0:0] icmp_ln704_reg_731;
wire   [12:0] sub122_fu_429_p2;
reg   [12:0] sub122_reg_736;
wire   [0:0] cmp125_fu_435_p2;
reg   [0:0] cmp125_reg_741;
wire   [0:0] icmp10_fu_451_p2;
reg   [0:0] icmp10_reg_746;
wire   [0:0] cmp125_2_fu_457_p2;
reg   [0:0] cmp125_2_reg_751;
wire   [12:0] trunc_ln658_2_fu_477_p4;
reg   [12:0] trunc_ln658_2_reg_775;
reg   [0:0] icmp_ln662_reg_780;
wire   [12:0] sub44_fu_499_p2;
reg   [12:0] sub44_reg_785;
wire   [0:0] cmp47_fu_505_p2;
reg   [0:0] cmp47_reg_790;
wire   [0:0] icmp_fu_521_p2;
reg   [0:0] icmp_reg_795;
wire   [0:0] cmp47_2_fu_527_p2;
reg   [0:0] cmp47_2_reg_800;
reg   [7:0] p_lcssa127141_load_reg_808;
wire    ap_CS_fsm_state3;
reg   [7:0] p_lcssa128144_load_reg_813;
wire   [0:0] trunc_ln753_fu_558_p1;
reg   [0:0] trunc_ln753_reg_818;
reg   [7:0] p_lcssa109119_load_reg_826;
reg   [7:0] p_lcssa110122_load_reg_831;
reg   [7:0] p_lcssa92101_load_reg_839;
reg   [7:0] p_lcssa93104_load_reg_844;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_write;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_write;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out_ap_vld;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1_ap_vld;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_write;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out_ap_vld;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1_ap_vld;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_write;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out_ap_vld;
wire   [7:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1_ap_vld;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [7:0] p_lcssa128144_fu_154;
reg   [7:0] p_lcssa127141_fu_150;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [7:0] p_lcssa110122_fu_166;
reg   [7:0] p_lcssa109119_fu_162;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg   [7:0] p_lcssa93104_fu_178;
reg   [7:0] p_lcssa92101_fu_174;
reg   [11:0] y_2_fu_146;
wire   [11:0] y_8_fu_546_p2;
wire   [0:0] icmp_ln753_fu_541_p2;
reg   [11:0] y_1_fu_158;
wire   [11:0] y_6_fu_575_p2;
wire   [0:0] icmp_ln712_fu_570_p2;
reg   [11:0] y_fu_170;
wire   [11:0] y_4_fu_600_p2;
wire   [0:0] icmp_ln670_fu_595_p2;
wire   [1:0] grp_fu_270_p4;
wire   [15:0] zext_ln741_fu_288_p1;
wire   [15:0] add_ln741_fu_291_p2;
wire   [2:0] remainPix_4_fu_285_p1;
wire   [3:0] zext_ln743_fu_307_p1;
wire   [3:0] remainPix_5_fu_317_p3;
wire   [2:0] tmp_2_fu_337_p4;
wire   [1:0] tmp_3_fu_359_p4;
wire   [15:0] zext_ln700_fu_398_p1;
wire   [15:0] add_ln700_fu_401_p2;
wire   [2:0] zext_ln702_fu_417_p1;
wire   [2:0] remainPix_3_fu_421_p3;
wire   [1:0] tmp_1_fu_441_p4;
wire   [15:0] zext_ln658_fu_468_p1;
wire   [15:0] add_ln658_fu_471_p2;
wire   [2:0] zext_ln660_fu_487_p1;
wire   [2:0] remainPix_1_fu_491_p3;
wire   [1:0] tmp_fu_511_p4;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg = 1'b0;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg = 1'b0;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg = 1'b0;
#0 y_2_fu_146 = 12'd0;
#0 y_1_fu_158 = 12'd0;
#0 y_fu_170 = 12'd0;
end

system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(3'd0),
    .img_fifo_cap(3'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_img_read),
    .p_lcssa128144(p_lcssa128144_load_reg_813),
    .p_lcssa127141(p_lcssa127141_load_reg_808),
    .trunc_ln741_2(trunc_ln741_2_reg_657),
    .bytePlanes_plane1_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_din),
    .bytePlanes_plane1_num_data_valid(11'd0),
    .bytePlanes_plane1_fifo_cap(11'd0),
    .bytePlanes_plane1_full_n(bytePlanes_plane1_full_n),
    .bytePlanes_plane1_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_write),
    .bytePlanes_plane0_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_din),
    .bytePlanes_plane0_num_data_valid(11'd0),
    .bytePlanes_plane0_fifo_cap(11'd0),
    .bytePlanes_plane0_full_n(bytePlanes_plane0_full_n),
    .bytePlanes_plane0_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_write),
    .VideoFormat_val(VideoFormat_val),
    .empty(trunc_ln753_reg_818),
    .icmp_ln745(icmp_ln745_reg_662),
    .cmp216_6(cmp216_6_reg_702),
    .cmp216_5(cmp216_5_reg_697),
    .cmp216_4(cmp216_4_reg_692),
    .icmp16(icmp16_reg_687),
    .cmp216_2(cmp216_2_reg_682),
    .icmp13(icmp13_reg_677),
    .sub213_cast58(sub213_reg_667),
    .cmp216(cmp216_reg_672),
    .p_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out),
    .p_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out_ap_vld),
    .p_out1(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1),
    .p_out1_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1_ap_vld)
);

system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(3'd0),
    .img_fifo_cap(3'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_img_read),
    .p_lcssa110122(p_lcssa110122_load_reg_831),
    .p_lcssa109119(p_lcssa109119_load_reg_826),
    .trunc_ln700_2(trunc_ln700_2_reg_726),
    .bytePlanes_plane0_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_din),
    .bytePlanes_plane0_num_data_valid(11'd0),
    .bytePlanes_plane0_fifo_cap(11'd0),
    .bytePlanes_plane0_full_n(bytePlanes_plane0_full_n),
    .bytePlanes_plane0_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_write),
    .icmp_ln704(icmp_ln704_reg_731),
    .cmp125_2(cmp125_2_reg_751),
    .icmp10(icmp10_reg_746),
    .sub122_cast57(sub122_reg_736),
    .cmp125(cmp125_reg_741),
    .p_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out),
    .p_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out_ap_vld),
    .p_out1(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1),
    .p_out1_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1_ap_vld)
);

system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(3'd0),
    .img_fifo_cap(3'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_img_read),
    .p_lcssa93104(p_lcssa93104_load_reg_844),
    .p_lcssa92101(p_lcssa92101_load_reg_839),
    .trunc_ln658_2(trunc_ln658_2_reg_775),
    .bytePlanes_plane0_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_din),
    .bytePlanes_plane0_num_data_valid(11'd0),
    .bytePlanes_plane0_fifo_cap(11'd0),
    .bytePlanes_plane0_full_n(bytePlanes_plane0_full_n),
    .bytePlanes_plane0_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_write),
    .icmp_ln662(icmp_ln662_reg_780),
    .cmp47_2(cmp47_2_reg_800),
    .icmp(icmp_reg_795),
    .sub44_cast56(sub44_reg_785),
    .cmp47(cmp47_reg_790),
    .p_out(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out),
    .p_out_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out_ap_vld),
    .p_out1(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1),
    .p_out1_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & ((6'd43 == VideoFormat_val_read_read_fu_196_p2) | ((6'd42 == VideoFormat_val_read_read_fu_196_p2) | ((6'd41 == VideoFormat_val_read_read_fu_196_p2) | ((6'd11 == VideoFormat_val_read_read_fu_196_p2) | ((6'd10 == VideoFormat_val_read_read_fu_196_p2) | ((6'd27 == VideoFormat_val_read_read_fu_196_p2) | ((6'd16 == VideoFormat_val_read_read_fu_196_p2) | ((6'd15 == VideoFormat_val_read_read_fu_196_p2) | ((((~(6'd12 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd28 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd19 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd18 == VideoFormat_val_read_read_fu_196_p2)) | (~(6'd12 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd28 == VideoFormat_val_read_read_fu_196_p2) & (icmp_ln753_fu_541_p2 == 1'd1))) | ((icmp_ln712_fu_570_p2 == 1'd1) & (6'd28 == VideoFormat_val_read_read_fu_196_p2))) | ((icmp_ln670_fu_595_p2 == 1'd1) & (6'd12 == VideoFormat_val_read_read_fu_196_p2))))))))))))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((6'd28 == VideoFormat_val_read_read_fu_196_p2)) begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            y_1_fu_158 <= 12'd0;
        end else if (((icmp_ln712_fu_570_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            y_1_fu_158 <= y_6_fu_575_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((6'd19 == VideoFormat_val_read_read_fu_196_p2) | (6'd18 == VideoFormat_val_read_read_fu_196_p2)))) begin
        y_2_fu_146 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (((6'd19 == VideoFormat_val_read_read_fu_196_p2) & (icmp_ln753_fu_541_p2 == 1'd0)) | ((icmp_ln753_fu_541_p2 == 1'd0) & (6'd18 == VideoFormat_val_read_read_fu_196_p2))))) begin
        y_2_fu_146 <= y_8_fu_546_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((6'd12 == VideoFormat_val_read_read_fu_196_p2)) begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            y_fu_170 <= 12'd0;
        end else if (((icmp_ln670_fu_595_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            y_fu_170 <= y_4_fu_600_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp125_2_reg_751 <= cmp125_2_fu_457_p2;
        cmp125_reg_741 <= cmp125_fu_435_p2;
        cmp216_2_reg_682 <= cmp216_2_fu_353_p2;
        cmp216_4_reg_692 <= cmp216_4_fu_375_p2;
        cmp216_5_reg_697 <= cmp216_5_fu_381_p2;
        cmp216_6_reg_702 <= cmp216_6_fu_387_p2;
        cmp216_reg_672 <= cmp216_fu_331_p2;
        cmp47_2_reg_800 <= cmp47_2_fu_527_p2;
        cmp47_reg_790 <= cmp47_fu_505_p2;
        icmp10_reg_746 <= icmp10_fu_451_p2;
        icmp13_reg_677 <= icmp13_fu_347_p2;
        icmp16_reg_687 <= icmp16_fu_369_p2;
        icmp_ln662_reg_780 <= grp_fu_279_p2;
        icmp_ln704_reg_731 <= grp_fu_279_p2;
        icmp_ln745_reg_662 <= icmp_ln745_fu_311_p2;
        icmp_reg_795 <= icmp_fu_521_p2;
        sub122_reg_736 <= sub122_fu_429_p2;
        sub213_reg_667 <= sub213_fu_325_p2;
        sub44_reg_785 <= sub44_fu_499_p2;
        trunc_ln658_2_reg_775 <= {{add_ln658_fu_471_p2[15:3]}};
        trunc_ln700_2_reg_726 <= {{add_ln700_fu_401_p2[15:3]}};
        trunc_ln741_2_reg_657 <= {{add_ln741_fu_291_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        p_lcssa109119_fu_162 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        p_lcssa109119_load_reg_826 <= p_lcssa109119_fu_162;
        p_lcssa110122_load_reg_831 <= p_lcssa110122_fu_166;
        p_lcssa127141_load_reg_808 <= p_lcssa127141_fu_150;
        p_lcssa128144_load_reg_813 <= p_lcssa128144_fu_154;
        p_lcssa92101_load_reg_839 <= p_lcssa92101_fu_174;
        p_lcssa93104_load_reg_844 <= p_lcssa93104_fu_178;
        trunc_ln753_reg_818 <= trunc_ln753_fu_558_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        p_lcssa110122_fu_166 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_p_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1_ap_vld == 1'b1))) begin
        p_lcssa127141_fu_150 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out_ap_vld == 1'b1))) begin
        p_lcssa128144_fu_154 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_p_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        p_lcssa92101_fu_174 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        p_lcssa93104_fu_178 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_p_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        widthInPix_reg_617 <= WidthInBytes_val_dout;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_val2_c_blk_n = WidthInBytes_val2_c_full_n;
    end else begin
        WidthInBytes_val2_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_val2_c_write = 1'b1;
    end else begin
        WidthInBytes_val2_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_val_blk_n = WidthInBytes_val_empty_n;
    end else begin
        WidthInBytes_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_val_read = 1'b1;
    end else begin
        WidthInBytes_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((6'd43 == VideoFormat_val_read_read_fu_196_p2) | ((6'd42 == VideoFormat_val_read_read_fu_196_p2) | ((6'd41 == VideoFormat_val_read_read_fu_196_p2) | ((6'd11 == VideoFormat_val_read_read_fu_196_p2) | ((6'd10 == VideoFormat_val_read_read_fu_196_p2) | ((6'd27 == VideoFormat_val_read_read_fu_196_p2) | ((6'd16 == VideoFormat_val_read_read_fu_196_p2) | ((6'd15 == VideoFormat_val_read_read_fu_196_p2) | ((((~(6'd12 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd28 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd19 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd18 == VideoFormat_val_read_read_fu_196_p2)) | (~(6'd12 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd28 == VideoFormat_val_read_read_fu_196_p2) & (icmp_ln753_fu_541_p2 == 1'd1))) | ((icmp_ln712_fu_570_p2 == 1'd1) & (6'd28 == VideoFormat_val_read_read_fu_196_p2))) | ((icmp_ln670_fu_595_p2 == 1'd1) & (6'd12 == VideoFormat_val_read_read_fu_196_p2))))))))))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & ((6'd43 == VideoFormat_val_read_read_fu_196_p2) | ((6'd42 == VideoFormat_val_read_read_fu_196_p2) | ((6'd41 == VideoFormat_val_read_read_fu_196_p2) | ((6'd11 == VideoFormat_val_read_read_fu_196_p2) | ((6'd10 == VideoFormat_val_read_read_fu_196_p2) | ((6'd27 == VideoFormat_val_read_read_fu_196_p2) | ((6'd16 == VideoFormat_val_read_read_fu_196_p2) | ((6'd15 == VideoFormat_val_read_read_fu_196_p2) | ((((~(6'd12 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd28 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd19 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd18 == VideoFormat_val_read_read_fu_196_p2)) | (~(6'd12 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd28 == VideoFormat_val_read_read_fu_196_p2) & (icmp_ln753_fu_541_p2 == 1'd1))) | ((icmp_ln712_fu_570_p2 == 1'd1) & (6'd28 == VideoFormat_val_read_read_fu_196_p2))) | ((icmp_ln670_fu_595_p2 == 1'd1) & (6'd12 == VideoFormat_val_read_read_fu_196_p2))))))))))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bytePlanes_plane0_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_din;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        bytePlanes_plane0_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_din;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        bytePlanes_plane0_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_din;
    end else begin
        bytePlanes_plane0_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        bytePlanes_plane0_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_bytePlanes_plane0_write;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        bytePlanes_plane0_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_bytePlanes_plane0_write;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        bytePlanes_plane0_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane0_write;
    end else begin
        bytePlanes_plane0_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        bytePlanes_plane1_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_write;
    end else begin
        bytePlanes_plane1_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_img_read;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_img_read;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_img_read;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & ((6'd43 == VideoFormat_val_read_read_fu_196_p2) | ((6'd42 == VideoFormat_val_read_read_fu_196_p2) | ((6'd41 == VideoFormat_val_read_read_fu_196_p2) | ((6'd11 == VideoFormat_val_read_read_fu_196_p2) | ((6'd10 == VideoFormat_val_read_read_fu_196_p2) | ((6'd27 == VideoFormat_val_read_read_fu_196_p2) | ((6'd16 == VideoFormat_val_read_read_fu_196_p2) | ((6'd15 == VideoFormat_val_read_read_fu_196_p2) | ((((~(6'd12 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd28 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd19 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd18 == VideoFormat_val_read_read_fu_196_p2)) | (~(6'd12 == VideoFormat_val_read_read_fu_196_p2) & ~(6'd28 == VideoFormat_val_read_read_fu_196_p2) & (icmp_ln753_fu_541_p2 == 1'd1))) | ((icmp_ln712_fu_570_p2 == 1'd1) & (6'd28 == VideoFormat_val_read_read_fu_196_p2))) | ((icmp_ln670_fu_595_p2 == 1'd1) & (6'd12 == VideoFormat_val_read_read_fu_196_p2))))))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln670_fu_595_p2 == 1'd0) & (6'd12 == VideoFormat_val_read_read_fu_196_p2) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if (((icmp_ln712_fu_570_p2 == 1'd0) & (6'd28 == VideoFormat_val_read_read_fu_196_p2) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign VideoFormat_val_read_read_fu_196_p2 = VideoFormat_val;

assign WidthInBytes_val2_c_din = WidthInBytes_val_dout;

assign add_ln658_fu_471_p2 = (zext_ln658_fu_468_p1 + 16'd7);

assign add_ln700_fu_401_p2 = (zext_ln700_fu_398_p1 + 16'd7);

assign add_ln741_fu_291_p2 = (zext_ln741_fu_288_p1 + 16'd7);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((1'b0 == WidthInBytes_val2_c_full_n) | (1'b0 == WidthInBytes_val_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign bytePlanes_plane1_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_bytePlanes_plane1_din;

assign cmp125_2_fu_457_p2 = ((remainPix_3_fu_421_p3 > 3'd2) ? 1'b1 : 1'b0);

assign cmp125_fu_435_p2 = ((remainPix_3_fu_421_p3 != 3'd0) ? 1'b1 : 1'b0);

assign cmp216_2_fu_353_p2 = ((remainPix_5_fu_317_p3 > 4'd2) ? 1'b1 : 1'b0);

assign cmp216_4_fu_375_p2 = ((remainPix_5_fu_317_p3 > 4'd4) ? 1'b1 : 1'b0);

assign cmp216_5_fu_381_p2 = ((remainPix_5_fu_317_p3 > 4'd5) ? 1'b1 : 1'b0);

assign cmp216_6_fu_387_p2 = ((remainPix_5_fu_317_p3 > 4'd6) ? 1'b1 : 1'b0);

assign cmp216_fu_331_p2 = ((remainPix_5_fu_317_p3 != 4'd0) ? 1'b1 : 1'b0);

assign cmp47_2_fu_527_p2 = ((remainPix_1_fu_491_p3 > 3'd2) ? 1'b1 : 1'b0);

assign cmp47_fu_505_p2 = ((remainPix_1_fu_491_p3 != 3'd0) ? 1'b1 : 1'b0);

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_674_1_fu_252_ap_start_reg;

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_716_5_fu_234_ap_start_reg;

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_757_8_fu_208_ap_start_reg;

assign grp_fu_270_p4 = {{widthInPix_reg_617[2:1]}};

assign grp_fu_279_p2 = ((grp_fu_270_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp10_fu_451_p2 = ((tmp_1_fu_441_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp13_fu_347_p2 = ((tmp_2_fu_337_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp16_fu_369_p2 = ((tmp_3_fu_359_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_fu_521_p2 = ((tmp_fu_511_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln670_fu_595_p2 = ((y_fu_170 == Height_val) ? 1'b1 : 1'b0);

assign icmp_ln712_fu_570_p2 = ((y_1_fu_158 == Height_val) ? 1'b1 : 1'b0);

assign icmp_ln745_fu_311_p2 = ((remainPix_4_fu_285_p1 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln753_fu_541_p2 = ((y_2_fu_146 == Height_val) ? 1'b1 : 1'b0);

assign remainPix_1_fu_491_p3 = ((grp_fu_279_p2[0:0] == 1'b1) ? 3'd4 : zext_ln660_fu_487_p1);

assign remainPix_3_fu_421_p3 = ((grp_fu_279_p2[0:0] == 1'b1) ? 3'd4 : zext_ln702_fu_417_p1);

assign remainPix_4_fu_285_p1 = widthInPix_reg_617[2:0];

assign remainPix_5_fu_317_p3 = ((icmp_ln745_fu_311_p2[0:0] == 1'b1) ? 4'd8 : zext_ln743_fu_307_p1);

assign sub122_fu_429_p2 = ($signed(trunc_ln700_2_fu_407_p4) + $signed(13'd8191));

assign sub213_fu_325_p2 = ($signed(trunc_ln741_2_fu_297_p4) + $signed(13'd8191));

assign sub44_fu_499_p2 = ($signed(trunc_ln658_2_fu_477_p4) + $signed(13'd8191));

assign tmp_1_fu_441_p4 = {{remainPix_3_fu_421_p3[2:1]}};

assign tmp_2_fu_337_p4 = {{remainPix_5_fu_317_p3[3:1]}};

assign tmp_3_fu_359_p4 = {{remainPix_5_fu_317_p3[3:2]}};

assign tmp_fu_511_p4 = {{remainPix_1_fu_491_p3[2:1]}};

assign trunc_ln658_2_fu_477_p4 = {{add_ln658_fu_471_p2[15:3]}};

assign trunc_ln700_2_fu_407_p4 = {{add_ln700_fu_401_p2[15:3]}};

assign trunc_ln741_2_fu_297_p4 = {{add_ln741_fu_291_p2[15:3]}};

assign trunc_ln753_fu_558_p1 = y_2_fu_146[0:0];

assign y_4_fu_600_p2 = (y_fu_170 + 12'd1);

assign y_6_fu_575_p2 = (y_1_fu_158 + 12'd1);

assign y_8_fu_546_p2 = (y_2_fu_146 + 12'd1);

assign zext_ln658_fu_468_p1 = widthInPix_reg_617;

assign zext_ln660_fu_487_p1 = grp_fu_270_p4;

assign zext_ln700_fu_398_p1 = widthInPix_reg_617;

assign zext_ln702_fu_417_p1 = grp_fu_270_p4;

assign zext_ln741_fu_288_p1 = widthInPix_reg_617;

assign zext_ln743_fu_307_p1 = remainPix_4_fu_285_p1;

endmodule //system_v_frmbuf_wr_0_0_MultiPixStream2Bytes
