# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.srcs/sources_1/bd/system/ip/system_rgb2dvi_1_0/system_rgb2dvi_1_0.xci
# IP: The module: 'system_rgb2dvi_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.gen/sources_1/bd/system/ip/system_rgb2dvi_1_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rgb2dvi_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.gen/sources_1/bd/system/ip/system_rgb2dvi_1_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rgb2dvi_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.gen/sources_1/bd/system/ip/system_rgb2dvi_1_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rgb2dvi_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.srcs/sources_1/bd/system/ip/system_rgb2dvi_1_0/system_rgb2dvi_1_0.xci
# IP: The module: 'system_rgb2dvi_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.gen/sources_1/bd/system/ip/system_rgb2dvi_1_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rgb2dvi_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.gen/sources_1/bd/system/ip/system_rgb2dvi_1_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rgb2dvi_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/hdway/Documents/vivado/TER/PmodENC_Linux/hw_with_enc/hw_with_enc.gen/sources_1/bd/system/ip/system_rgb2dvi_1_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rgb2dvi_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
