-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    img_num_data_valid : IN STD_LOGIC_VECTOR (1 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (1 downto 0);
    img_empty_n : IN STD_LOGIC;
    img_read : OUT STD_LOGIC;
    bytePlanes_plane0_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    bytePlanes_plane0_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane0_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane0_full_n : IN STD_LOGIC;
    bytePlanes_plane0_write : OUT STD_LOGIC;
    bytePlanes_plane1_din : OUT STD_LOGIC_VECTOR (63 downto 0);
    bytePlanes_plane1_num_data_valid : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane1_fifo_cap : IN STD_LOGIC_VECTOR (10 downto 0);
    bytePlanes_plane1_full_n : IN STD_LOGIC;
    bytePlanes_plane1_write : OUT STD_LOGIC;
    trunc_ln571_1 : IN STD_LOGIC_VECTOR (12 downto 0);
    VideoFormat_load : IN STD_LOGIC_VECTOR (5 downto 0);
    trunc_ln : IN STD_LOGIC_VECTOR (0 downto 0);
    icmp_ln576 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp212_6 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp212_5 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp212_4 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp212_3 : IN STD_LOGIC_VECTOR (0 downto 0);
    cmp212_2 : IN STD_LOGIC_VECTOR (0 downto 0);
    sub209_cast62 : IN STD_LOGIC_VECTOR (12 downto 0);
    cmp212_1 : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of system_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_586_8 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_pp0_stage2 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_pp0_stage3 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp0_stage4 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_pp0_stage5 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_pp0_stage6 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_pp0_stage7 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv6_13 : STD_LOGIC_VECTOR (5 downto 0) := "010011";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal icmp_ln586_reg_543 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage1_iter0 : BOOLEAN;
    signal and_ln605_reg_558 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln605_reg_558_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state10_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage1 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage7 : signal is "none";
    signal or_ln590_5_reg_609 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op93_read_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage7_iter0 : BOOLEAN;
    signal ap_block_pp0_stage7_subdone : BOOLEAN;
    signal bytePlanes_plane1_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal bytePlanes_plane0_blk_n : STD_LOGIC;
    signal img_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage2 : signal is "none";
    signal ap_block_pp0_stage2 : BOOLEAN;
    signal or_ln590_reg_574 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage3 : signal is "none";
    signal ap_block_pp0_stage3 : BOOLEAN;
    signal or_ln590_1_reg_583 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage4 : signal is "none";
    signal ap_block_pp0_stage4 : BOOLEAN;
    signal or_ln590_2_reg_592 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage5 : signal is "none";
    signal ap_block_pp0_stage5 : BOOLEAN;
    signal or_ln590_3_reg_601 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage6 : signal is "none";
    signal ap_block_pp0_stage6 : BOOLEAN;
    signal or_ln590_4_reg_605 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage7 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal or_ln590_6_reg_613 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_pix_UV_1_reg_176 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_Y_1_reg_186 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_UV_2_reg_196 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_Y_2_reg_207 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_UV_3_reg_218 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_Y_3_reg_229 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_UV_4_reg_240 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_Y_4_reg_251 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_UV_5_reg_262 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_Y_5_reg_273 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_UV_6_reg_284 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_Y_6_reg_295 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_predicate_op52_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage2_iter0 : BOOLEAN;
    signal ap_block_pp0_stage2_11001 : BOOLEAN;
    signal ap_predicate_op68_read_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage4_iter0 : BOOLEAN;
    signal ap_block_pp0_stage4_11001 : BOOLEAN;
    signal ap_predicate_op86_read_state7 : BOOLEAN;
    signal ap_block_state7_pp0_stage6_iter0 : BOOLEAN;
    signal ap_block_pp0_stage6_11001 : BOOLEAN;
    signal ap_predicate_op60_read_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_pp0_stage3_11001 : BOOLEAN;
    signal ap_predicate_op79_read_state6 : BOOLEAN;
    signal ap_block_state6_pp0_stage5_iter0 : BOOLEAN;
    signal ap_block_pp0_stage5_11001 : BOOLEAN;
    signal ap_block_pp0_stage7_11001 : BOOLEAN;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_predicate_op100_read_state9 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln586_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp210_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp210_reg_547 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln605_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal in_pix_Y_fu_401_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_pix_Y_reg_562 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal in_pix_UV_reg_568 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln590_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln591_fu_409_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln590_1_fu_413_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln591_1_fu_417_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln590_2_fu_421_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln591_3_fu_425_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln590_3_fu_429_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln590_4_fu_433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln590_5_fu_437_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln590_6_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln591_5_fu_445_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln591_7_fu_449_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln591_9_fu_453_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln591_11_fu_457_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter0_reg : STD_LOGIC := '0';
    signal ap_phi_reg_pp0_iter0_in_pix_UV_1_reg_176 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_Y_1_reg_186 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_UV_2_reg_196 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_Y_2_reg_207 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_UV_3_reg_218 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_Y_3_reg_229 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_UV_4_reg_240 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_Y_4_reg_251 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_UV_5_reg_262 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_Y_5_reg_273 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_UV_6_reg_284 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_in_pix_UV_6_reg_284 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_Y_6_reg_295 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_in_pix_Y_6_reg_295 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_UV_7_reg_306 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_in_pix_UV_7_reg_306 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_in_pix_Y_7_reg_316 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_in_pix_Y_7_reg_316 : STD_LOGIC_VECTOR (7 downto 0);
    signal x_fu_86 : STD_LOGIC_VECTOR (12 downto 0);
    signal x_2_fu_368_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_1 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_block_pp0_stage1_01001 : BOOLEAN;
    signal zext_ln586_fu_374_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sub209_cast62_cast_fu_350_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln605_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_idle_pp0_1to1 : STD_LOGIC;
    signal ap_block_pp0_stage2_subdone : BOOLEAN;
    signal ap_block_pp0_stage3_subdone : BOOLEAN;
    signal ap_block_pp0_stage4_subdone : BOOLEAN;
    signal ap_block_pp0_stage5_subdone : BOOLEAN;
    signal ap_block_pp0_stage6_subdone : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_670 : BOOLEAN;
    signal ap_condition_674 : BOOLEAN;
    signal ap_condition_678 : BOOLEAN;
    signal ap_condition_682 : BOOLEAN;
    signal ap_condition_685 : BOOLEAN;
    signal ap_condition_689 : BOOLEAN;
    signal ap_condition_310 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component system_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component system_v_frmbuf_wr_0_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage1,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
                    ap_enable_reg_pp0_iter0_reg <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter0_in_pix_UV_2_reg_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_670)) then
                if ((or_ln590_1_reg_583 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_in_pix_UV_2_reg_196 <= ap_phi_reg_pp0_iter0_in_pix_UV_1_reg_176;
                elsif ((or_ln590_1_reg_583 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_in_pix_UV_2_reg_196 <= img_dout(15 downto 8);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_in_pix_UV_3_reg_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_674)) then
                if ((or_ln590_2_reg_592 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_in_pix_UV_3_reg_218 <= ap_phi_reg_pp0_iter0_in_pix_UV_2_reg_196;
                elsif ((or_ln590_2_reg_592 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_in_pix_UV_3_reg_218 <= img_dout(15 downto 8);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_in_pix_UV_4_reg_240_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_678)) then
                if ((or_ln590_3_reg_601 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_in_pix_UV_4_reg_240 <= ap_phi_reg_pp0_iter0_in_pix_UV_3_reg_218;
                elsif ((or_ln590_3_reg_601 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_in_pix_UV_4_reg_240 <= img_dout(15 downto 8);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_in_pix_UV_5_reg_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_682)) then
                if ((or_ln590_4_reg_605 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_in_pix_UV_5_reg_262 <= ap_phi_reg_pp0_iter0_in_pix_UV_4_reg_240;
                elsif ((or_ln590_4_reg_605 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_in_pix_UV_5_reg_262 <= img_dout(15 downto 8);
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_in_pix_Y_1_reg_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                if ((ap_const_boolean_1 = ap_condition_689)) then 
                    ap_phi_reg_pp0_iter0_in_pix_Y_1_reg_186 <= in_pix_Y_fu_401_p1;
                elsif ((ap_const_boolean_1 = ap_condition_685)) then 
                    ap_phi_reg_pp0_iter0_in_pix_Y_1_reg_186 <= trunc_ln591_fu_409_p1;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_in_pix_Y_2_reg_207_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_670)) then
                if ((or_ln590_1_reg_583 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_in_pix_Y_2_reg_207 <= ap_phi_reg_pp0_iter0_in_pix_Y_1_reg_186;
                elsif ((or_ln590_1_reg_583 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_in_pix_Y_2_reg_207 <= trunc_ln591_1_fu_417_p1;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_in_pix_Y_3_reg_229_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_674)) then
                if ((or_ln590_2_reg_592 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_in_pix_Y_3_reg_229 <= ap_phi_reg_pp0_iter0_in_pix_Y_2_reg_207;
                elsif ((or_ln590_2_reg_592 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_in_pix_Y_3_reg_229 <= trunc_ln591_3_fu_425_p1;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_in_pix_Y_4_reg_251_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_678)) then
                if ((or_ln590_3_reg_601 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_in_pix_Y_4_reg_251 <= ap_phi_reg_pp0_iter0_in_pix_Y_3_reg_229;
                elsif ((or_ln590_3_reg_601 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_in_pix_Y_4_reg_251 <= trunc_ln591_5_fu_445_p1;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter0_in_pix_Y_5_reg_273_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_682)) then
                if ((or_ln590_4_reg_605 = ap_const_lv1_0)) then 
                    ap_phi_reg_pp0_iter0_in_pix_Y_5_reg_273 <= ap_phi_reg_pp0_iter0_in_pix_Y_4_reg_251;
                elsif ((or_ln590_4_reg_605 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter0_in_pix_Y_5_reg_273 <= trunc_ln591_7_fu_449_p1;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_in_pix_UV_6_reg_284_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if (((or_ln590_5_reg_609 = ap_const_lv1_0) and (icmp_ln586_reg_543 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_in_pix_UV_6_reg_284 <= ap_phi_reg_pp0_iter0_in_pix_UV_5_reg_262;
                elsif (((or_ln590_5_reg_609 = ap_const_lv1_1) and (icmp_ln586_reg_543 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_in_pix_UV_6_reg_284 <= img_dout(15 downto 8);
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_in_pix_UV_6_reg_284 <= ap_phi_reg_pp0_iter0_in_pix_UV_6_reg_284;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_in_pix_UV_7_reg_306_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln590_6_reg_613 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_in_pix_UV_7_reg_306 <= ap_phi_reg_pp0_iter1_in_pix_UV_6_reg_284;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln590_6_reg_613 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_in_pix_UV_7_reg_306 <= img_dout(15 downto 8);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_in_pix_UV_7_reg_306 <= ap_phi_reg_pp0_iter0_in_pix_UV_7_reg_306;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_in_pix_Y_6_reg_295_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_310)) then
                if (((or_ln590_5_reg_609 = ap_const_lv1_0) and (icmp_ln586_reg_543 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_in_pix_Y_6_reg_295 <= ap_phi_reg_pp0_iter0_in_pix_Y_5_reg_273;
                elsif (((or_ln590_5_reg_609 = ap_const_lv1_1) and (icmp_ln586_reg_543 = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter1_in_pix_Y_6_reg_295 <= trunc_ln591_9_fu_453_p1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_in_pix_Y_6_reg_295 <= ap_phi_reg_pp0_iter0_in_pix_Y_6_reg_295;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_in_pix_Y_7_reg_316_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln590_6_reg_613 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_in_pix_Y_7_reg_316 <= ap_phi_reg_pp0_iter1_in_pix_Y_6_reg_295;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln590_6_reg_613 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter1_in_pix_Y_7_reg_316 <= trunc_ln591_11_fu_457_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
                ap_phi_reg_pp0_iter1_in_pix_Y_7_reg_316 <= ap_phi_reg_pp0_iter0_in_pix_Y_7_reg_316;
            end if; 
        end if;
    end process;

    x_fu_86_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln586_fu_362_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_86 <= x_2_fu_368_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_86 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln586_fu_362_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln605_reg_558 <= and_ln605_fu_390_p2;
                cmp210_reg_547 <= cmp210_fu_378_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln605_reg_558_pp0_iter1_reg <= and_ln605_reg_558;
                icmp_ln586_reg_543 <= icmp_ln586_fu_362_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (or_ln590_fu_405_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln590_reg_574 = ap_const_lv1_1)))) then
                ap_phi_reg_pp0_iter0_in_pix_UV_1_reg_176 <= img_dout(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                in_pix_UV_1_reg_176 <= ap_phi_reg_pp0_iter0_in_pix_UV_1_reg_176;
                in_pix_Y_1_reg_186 <= ap_phi_reg_pp0_iter0_in_pix_Y_1_reg_186;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                in_pix_UV_2_reg_196 <= ap_phi_reg_pp0_iter0_in_pix_UV_2_reg_196;
                in_pix_Y_2_reg_207 <= ap_phi_reg_pp0_iter0_in_pix_Y_2_reg_207;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5))) then
                in_pix_UV_3_reg_218 <= ap_phi_reg_pp0_iter0_in_pix_UV_3_reg_218;
                in_pix_Y_3_reg_229 <= ap_phi_reg_pp0_iter0_in_pix_Y_3_reg_229;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6))) then
                in_pix_UV_4_reg_240 <= ap_phi_reg_pp0_iter0_in_pix_UV_4_reg_240;
                in_pix_Y_4_reg_251 <= ap_phi_reg_pp0_iter0_in_pix_Y_4_reg_251;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then
                in_pix_UV_5_reg_262 <= ap_phi_reg_pp0_iter0_in_pix_UV_5_reg_262;
                in_pix_Y_5_reg_273 <= ap_phi_reg_pp0_iter0_in_pix_Y_5_reg_273;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                in_pix_UV_6_reg_284 <= ap_phi_reg_pp0_iter1_in_pix_UV_6_reg_284;
                in_pix_Y_6_reg_295 <= ap_phi_reg_pp0_iter1_in_pix_Y_6_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                in_pix_UV_reg_568 <= img_dout(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                in_pix_Y_reg_562 <= in_pix_Y_fu_401_p1;
                or_ln590_reg_574 <= or_ln590_fu_405_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2))) then
                or_ln590_1_reg_583 <= or_ln590_1_fu_413_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3))) then
                or_ln590_2_reg_592 <= or_ln590_2_fu_421_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4))) then
                or_ln590_3_reg_601 <= or_ln590_3_fu_429_p2;
                or_ln590_4_reg_605 <= or_ln590_4_fu_433_p2;
                or_ln590_5_reg_609 <= or_ln590_5_fu_437_p2;
                or_ln590_6_reg_613 <= or_ln590_6_fu_441_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage1_subdone, ap_condition_exit_pp0_iter0_stage1, ap_block_pp0_stage7_subdone, ap_block_pp0_stage0_subdone, ap_idle_pp0_1to1, ap_block_pp0_stage2_subdone, ap_block_pp0_stage3_subdone, ap_block_pp0_stage4_subdone, ap_block_pp0_stage5_subdone, ap_block_pp0_stage6_subdone, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_start_int = ap_const_logic_0) and (ap_idle_pp0_1to1 = ap_const_logic_1))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage1)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_pp0_stage2 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage2_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage2;
                end if;
            when ap_ST_fsm_pp0_stage3 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage3_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage3;
                end if;
            when ap_ST_fsm_pp0_stage4 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage4_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage4;
                end if;
            when ap_ST_fsm_pp0_stage5 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage5_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage5;
                end if;
            when ap_ST_fsm_pp0_stage6 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage6_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage6;
                end if;
            when ap_ST_fsm_pp0_stage7 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage7_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    and_ln605_fu_390_p2 <= (trunc_ln and icmp_ln605_fu_384_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage2 <= ap_CS_fsm(2);
    ap_CS_fsm_pp0_stage3 <= ap_CS_fsm(3);
    ap_CS_fsm_pp0_stage4 <= ap_CS_fsm(4);
    ap_CS_fsm_pp0_stage5 <= ap_CS_fsm(5);
    ap_CS_fsm_pp0_stage6 <= ap_CS_fsm(6);
    ap_CS_fsm_pp0_stage7 <= ap_CS_fsm(7);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, img_empty_n, ap_predicate_op100_read_state9)
    begin
                ap_block_pp0_stage0_11001 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op100_read_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, img_empty_n, ap_predicate_op100_read_state9)
    begin
                ap_block_pp0_stage0_subdone <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op100_read_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_01001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, img_empty_n, icmp_ln586_reg_543, bytePlanes_plane0_full_n, bytePlanes_plane1_full_n, and_ln605_reg_558_pp0_iter1_reg)
    begin
                ap_block_pp0_stage1_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((bytePlanes_plane0_full_n = ap_const_logic_0) or ((bytePlanes_plane1_full_n = ap_const_logic_0) and (ap_const_lv1_0 = and_ln605_reg_558_pp0_iter1_reg)))) or ((icmp_ln586_reg_543 = ap_const_lv1_0) and (img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage1_11001_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, img_empty_n, icmp_ln586_reg_543, bytePlanes_plane0_full_n, bytePlanes_plane1_full_n, and_ln605_reg_558_pp0_iter1_reg)
    begin
                ap_block_pp0_stage1_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((bytePlanes_plane0_full_n = ap_const_logic_0) or ((bytePlanes_plane1_full_n = ap_const_logic_0) and (ap_const_lv1_0 = and_ln605_reg_558_pp0_iter1_reg)))) or ((icmp_ln586_reg_543 = ap_const_lv1_0) and (img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, img_empty_n, icmp_ln586_reg_543, bytePlanes_plane0_full_n, bytePlanes_plane1_full_n, and_ln605_reg_558_pp0_iter1_reg)
    begin
                ap_block_pp0_stage1_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((bytePlanes_plane0_full_n = ap_const_logic_0) or ((bytePlanes_plane1_full_n = ap_const_logic_0) and (ap_const_lv1_0 = and_ln605_reg_558_pp0_iter1_reg)))) or ((icmp_ln586_reg_543 = ap_const_lv1_0) and (img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)));
    end process;

        ap_block_pp0_stage2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage2_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op52_read_state3)
    begin
                ap_block_pp0_stage2_11001 <= ((img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op52_read_state3 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage2_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op52_read_state3)
    begin
                ap_block_pp0_stage2_subdone <= ((img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op52_read_state3 = ap_const_boolean_1));
    end process;

        ap_block_pp0_stage3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage3_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op60_read_state4)
    begin
                ap_block_pp0_stage3_11001 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op60_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage3_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op60_read_state4)
    begin
                ap_block_pp0_stage3_subdone <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op60_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage4_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op68_read_state5)
    begin
                ap_block_pp0_stage4_11001 <= ((img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op68_read_state5 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage4_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op68_read_state5)
    begin
                ap_block_pp0_stage4_subdone <= ((img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op68_read_state5 = ap_const_boolean_1));
    end process;

        ap_block_pp0_stage5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage5_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op79_read_state6)
    begin
                ap_block_pp0_stage5_11001 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op79_read_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage5_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op79_read_state6)
    begin
                ap_block_pp0_stage5_subdone <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op79_read_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage6_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op86_read_state7)
    begin
                ap_block_pp0_stage6_11001 <= ((img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op86_read_state7 = ap_const_boolean_1));
    end process;


    ap_block_pp0_stage6_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op86_read_state7)
    begin
                ap_block_pp0_stage6_subdone <= ((img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op86_read_state7 = ap_const_boolean_1));
    end process;

        ap_block_pp0_stage7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage7_11001_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op93_read_state8)
    begin
                ap_block_pp0_stage7_11001 <= ((ap_predicate_op93_read_state8 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage7_subdone_assign_proc : process(ap_enable_reg_pp0_iter0, img_empty_n, ap_predicate_op93_read_state8)
    begin
                ap_block_pp0_stage7_subdone <= ((ap_predicate_op93_read_state8 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_state10_pp0_stage1_iter1_assign_proc : process(bytePlanes_plane0_full_n, bytePlanes_plane1_full_n, and_ln605_reg_558_pp0_iter1_reg)
    begin
                ap_block_state10_pp0_stage1_iter1 <= ((bytePlanes_plane0_full_n = ap_const_logic_0) or ((bytePlanes_plane1_full_n = ap_const_logic_0) and (ap_const_lv1_0 = and_ln605_reg_558_pp0_iter1_reg)));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage1_iter0_assign_proc : process(img_empty_n, icmp_ln586_reg_543)
    begin
                ap_block_state2_pp0_stage1_iter0 <= ((icmp_ln586_reg_543 = ap_const_lv1_0) and (img_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage2_iter0_assign_proc : process(img_empty_n, ap_predicate_op52_read_state3)
    begin
                ap_block_state3_pp0_stage2_iter0 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op52_read_state3 = ap_const_boolean_1));
    end process;


    ap_block_state4_pp0_stage3_iter0_assign_proc : process(img_empty_n, ap_predicate_op60_read_state4)
    begin
                ap_block_state4_pp0_stage3_iter0 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op60_read_state4 = ap_const_boolean_1));
    end process;


    ap_block_state5_pp0_stage4_iter0_assign_proc : process(img_empty_n, ap_predicate_op68_read_state5)
    begin
                ap_block_state5_pp0_stage4_iter0 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op68_read_state5 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp0_stage5_iter0_assign_proc : process(img_empty_n, ap_predicate_op79_read_state6)
    begin
                ap_block_state6_pp0_stage5_iter0 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op79_read_state6 = ap_const_boolean_1));
    end process;


    ap_block_state7_pp0_stage6_iter0_assign_proc : process(img_empty_n, ap_predicate_op86_read_state7)
    begin
                ap_block_state7_pp0_stage6_iter0 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op86_read_state7 = ap_const_boolean_1));
    end process;


    ap_block_state8_pp0_stage7_iter0_assign_proc : process(img_empty_n, ap_predicate_op93_read_state8)
    begin
                ap_block_state8_pp0_stage7_iter0 <= ((ap_predicate_op93_read_state8 = ap_const_boolean_1) and (img_empty_n = ap_const_logic_0));
    end process;


    ap_block_state9_pp0_stage0_iter1_assign_proc : process(img_empty_n, ap_predicate_op100_read_state9)
    begin
                ap_block_state9_pp0_stage0_iter1 <= ((img_empty_n = ap_const_logic_0) and (ap_predicate_op100_read_state9 = ap_const_boolean_1));
    end process;


    ap_condition_310_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_11001)
    begin
                ap_condition_310 <= ((ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7));
    end process;


    ap_condition_670_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln586_reg_543, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3_11001)
    begin
                ap_condition_670 <= ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3));
    end process;


    ap_condition_674_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln586_reg_543, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4_11001)
    begin
                ap_condition_674 <= ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4));
    end process;


    ap_condition_678_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln586_reg_543, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5_11001)
    begin
                ap_condition_678 <= ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5));
    end process;


    ap_condition_682_assign_proc : process(ap_enable_reg_pp0_iter0, icmp_ln586_reg_543, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6_11001)
    begin
                ap_condition_682 <= ((ap_const_boolean_0 = ap_block_pp0_stage6_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6));
    end process;


    ap_condition_685_assign_proc : process(ap_CS_fsm_pp0_stage2, or_ln590_reg_574, ap_block_pp0_stage2_11001)
    begin
                ap_condition_685 <= ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln590_reg_574 = ap_const_lv1_1));
    end process;


    ap_condition_689_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001, or_ln590_fu_405_p2)
    begin
                ap_condition_689 <= ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (or_ln590_fu_405_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1));
    end process;


    ap_condition_exit_pp0_iter0_stage1_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage1, icmp_ln586_reg_543, ap_block_pp0_stage1_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (icmp_ln586_reg_543 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_reg_pp0_iter0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0_reg, ap_start_int)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then 
            ap_enable_reg_pp0_iter0 <= ap_start_int;
        else 
            ap_enable_reg_pp0_iter0 <= ap_enable_reg_pp0_iter0_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_1to1_assign_proc : process(ap_enable_reg_pp0_iter1)
    begin
        if ((ap_enable_reg_pp0_iter1 = ap_const_logic_0)) then 
            ap_idle_pp0_1to1 <= ap_const_logic_1;
        else 
            ap_idle_pp0_1to1 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage1;
    ap_phi_reg_pp0_iter0_in_pix_UV_6_reg_284 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_in_pix_UV_7_reg_306 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_in_pix_Y_6_reg_295 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_in_pix_Y_7_reg_316 <= "XXXXXXXX";

    ap_predicate_op100_read_state9_assign_proc : process(icmp_ln586_reg_543, or_ln590_6_reg_613)
    begin
                ap_predicate_op100_read_state9 <= ((icmp_ln586_reg_543 = ap_const_lv1_0) and (or_ln590_6_reg_613 = ap_const_lv1_1));
    end process;


    ap_predicate_op52_read_state3_assign_proc : process(icmp_ln586_reg_543, or_ln590_reg_574)
    begin
                ap_predicate_op52_read_state3 <= ((icmp_ln586_reg_543 = ap_const_lv1_0) and (or_ln590_reg_574 = ap_const_lv1_1));
    end process;


    ap_predicate_op60_read_state4_assign_proc : process(icmp_ln586_reg_543, or_ln590_1_reg_583)
    begin
                ap_predicate_op60_read_state4 <= ((icmp_ln586_reg_543 = ap_const_lv1_0) and (or_ln590_1_reg_583 = ap_const_lv1_1));
    end process;


    ap_predicate_op68_read_state5_assign_proc : process(icmp_ln586_reg_543, or_ln590_2_reg_592)
    begin
                ap_predicate_op68_read_state5 <= ((icmp_ln586_reg_543 = ap_const_lv1_0) and (or_ln590_2_reg_592 = ap_const_lv1_1));
    end process;


    ap_predicate_op79_read_state6_assign_proc : process(icmp_ln586_reg_543, or_ln590_3_reg_601)
    begin
                ap_predicate_op79_read_state6 <= ((icmp_ln586_reg_543 = ap_const_lv1_0) and (or_ln590_3_reg_601 = ap_const_lv1_1));
    end process;


    ap_predicate_op86_read_state7_assign_proc : process(icmp_ln586_reg_543, or_ln590_4_reg_605)
    begin
                ap_predicate_op86_read_state7 <= ((icmp_ln586_reg_543 = ap_const_lv1_0) and (or_ln590_4_reg_605 = ap_const_lv1_1));
    end process;


    ap_predicate_op93_read_state8_assign_proc : process(icmp_ln586_reg_543, or_ln590_5_reg_609)
    begin
                ap_predicate_op93_read_state8 <= ((or_ln590_5_reg_609 = ap_const_lv1_1) and (icmp_ln586_reg_543 = ap_const_lv1_0));
    end process;


    ap_ready_int_assign_proc : process(ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage7, ap_block_pp0_stage7_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage7_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_86, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x_1 <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_x_1 <= x_fu_86;
        end if; 
    end process;


    bytePlanes_plane0_blk_n_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, bytePlanes_plane0_full_n, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bytePlanes_plane0_blk_n <= bytePlanes_plane0_full_n;
        else 
            bytePlanes_plane0_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bytePlanes_plane0_din <= (((((((ap_phi_reg_pp0_iter1_in_pix_Y_7_reg_316 & in_pix_Y_6_reg_295) & in_pix_Y_5_reg_273) & in_pix_Y_4_reg_251) & in_pix_Y_3_reg_229) & in_pix_Y_2_reg_207) & in_pix_Y_1_reg_186) & in_pix_Y_reg_562);

    bytePlanes_plane0_write_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bytePlanes_plane0_write <= ap_const_logic_1;
        else 
            bytePlanes_plane0_write <= ap_const_logic_0;
        end if; 
    end process;


    bytePlanes_plane1_blk_n_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, bytePlanes_plane1_full_n, and_ln605_reg_558_pp0_iter1_reg, ap_block_pp0_stage1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_const_lv1_0 = and_ln605_reg_558_pp0_iter1_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bytePlanes_plane1_blk_n <= bytePlanes_plane1_full_n;
        else 
            bytePlanes_plane1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    bytePlanes_plane1_din <= (((((((ap_phi_reg_pp0_iter1_in_pix_UV_7_reg_306 & in_pix_UV_6_reg_284) & in_pix_UV_5_reg_262) & in_pix_UV_4_reg_240) & in_pix_UV_3_reg_218) & in_pix_UV_2_reg_196) & in_pix_UV_1_reg_176) & in_pix_UV_reg_568);

    bytePlanes_plane1_write_assign_proc : process(ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, and_ln605_reg_558_pp0_iter1_reg, ap_block_pp0_stage1_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (ap_const_lv1_0 = and_ln605_reg_558_pp0_iter1_reg) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then 
            bytePlanes_plane1_write <= ap_const_logic_1;
        else 
            bytePlanes_plane1_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp210_fu_378_p2 <= "1" when (signed(zext_ln586_fu_374_p1) < signed(sub209_cast62_cast_fu_350_p1)) else "0";
    icmp_ln586_fu_362_p2 <= "1" when (ap_sig_allocacmp_x_1 = trunc_ln571_1) else "0";
    icmp_ln605_fu_384_p2 <= "1" when (VideoFormat_load = ap_const_lv6_13) else "0";

    img_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, img_empty_n, icmp_ln586_reg_543, ap_CS_fsm_pp0_stage7, ap_predicate_op93_read_state8, ap_block_pp0_stage1, ap_CS_fsm_pp0_stage2, ap_block_pp0_stage2, or_ln590_reg_574, ap_CS_fsm_pp0_stage3, ap_block_pp0_stage3, or_ln590_1_reg_583, ap_CS_fsm_pp0_stage4, ap_block_pp0_stage4, or_ln590_2_reg_592, ap_CS_fsm_pp0_stage5, ap_block_pp0_stage5, or_ln590_3_reg_601, ap_CS_fsm_pp0_stage6, ap_block_pp0_stage6, or_ln590_4_reg_605, ap_block_pp0_stage7, ap_block_pp0_stage0, or_ln590_6_reg_613)
    begin
        if ((((ap_predicate_op93_read_state8 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage7) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (or_ln590_6_reg_613 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage6) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (or_ln590_4_reg_605 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage5) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5) and (or_ln590_3_reg_601 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage4) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 
    = ap_CS_fsm_pp0_stage4) and (or_ln590_2_reg_592 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage3) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3) and (or_ln590_1_reg_583 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage2) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2) and (or_ln590_reg_574 = ap_const_lv1_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage1) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            img_blk_n <= img_empty_n;
        else 
            img_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_CS_fsm_pp0_stage1, icmp_ln586_reg_543, ap_CS_fsm_pp0_stage7, ap_predicate_op93_read_state8, ap_CS_fsm_pp0_stage2, ap_CS_fsm_pp0_stage3, ap_CS_fsm_pp0_stage4, ap_CS_fsm_pp0_stage5, ap_CS_fsm_pp0_stage6, ap_predicate_op52_read_state3, ap_block_pp0_stage2_11001, ap_predicate_op68_read_state5, ap_block_pp0_stage4_11001, ap_predicate_op86_read_state7, ap_block_pp0_stage6_11001, ap_predicate_op60_read_state4, ap_block_pp0_stage3_11001, ap_predicate_op79_read_state6, ap_block_pp0_stage5_11001, ap_block_pp0_stage7_11001, ap_predicate_op100_read_state9, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_predicate_op93_read_state8 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage7_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage7)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (icmp_ln586_reg_543 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op100_read_state9 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage5_11001) and (ap_predicate_op79_read_state6 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage5)) or ((ap_const_boolean_0 = ap_block_pp0_stage3_11001) and (ap_predicate_op60_read_state4 = ap_const_boolean_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage3)) or ((ap_const_boolean_0 
    = ap_block_pp0_stage6_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op86_read_state7 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage6)) or ((ap_const_boolean_0 = ap_block_pp0_stage4_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op68_read_state5 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage4)) or ((ap_const_boolean_0 = ap_block_pp0_stage2_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_predicate_op52_read_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage2)))) then 
            img_read <= ap_const_logic_1;
        else 
            img_read <= ap_const_logic_0;
        end if; 
    end process;

    in_pix_Y_fu_401_p1 <= img_dout(8 - 1 downto 0);
    or_ln590_1_fu_413_p2 <= (cmp212_2 or cmp210_reg_547);
    or_ln590_2_fu_421_p2 <= (cmp212_3 or cmp210_reg_547);
    or_ln590_3_fu_429_p2 <= (cmp212_4 or cmp210_reg_547);
    or_ln590_4_fu_433_p2 <= (cmp212_5 or cmp210_reg_547);
    or_ln590_5_fu_437_p2 <= (cmp212_6 or cmp210_reg_547);
    or_ln590_6_fu_441_p2 <= (icmp_ln576 or cmp210_reg_547);
    or_ln590_fu_405_p2 <= (cmp212_1 or cmp210_reg_547);
        sub209_cast62_cast_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sub209_cast62),14));

    trunc_ln591_11_fu_457_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln591_1_fu_417_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln591_3_fu_425_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln591_5_fu_445_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln591_7_fu_449_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln591_9_fu_453_p1 <= img_dout(8 - 1 downto 0);
    trunc_ln591_fu_409_p1 <= img_dout(8 - 1 downto 0);
    x_2_fu_368_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_1) + unsigned(ap_const_lv13_1));
    zext_ln586_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_x_1),14));
end behav;
